<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Riwayat_Dok-Pelaporan</name>
   <tag></tag>
   <elementGuidId>1b6bb751-371c-4a1e-be58-3035763b8745</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@onclick=&quot;lihatRiwayat('8455e158-1909-4009-a1b9-1decbf28fd09')&quot;]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.btn.btn-info.btn-sm</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=row[name=&quot;1  Riwayat kewajiban 2 Bulanan User 2025-10-16 Input Dokumen Persyaratan&quot;i] >> div</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>4032683e-c056-47a6-b2a8-0584cf78d69f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>lihatRiwayat('8455e158-1909-4009-a1b9-1decbf28fd09')</value>
      <webElementGuid>1028d869-fc8f-461e-aa95-ee07430ce8fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-info btn-sm</value>
      <webElementGuid>bd401d5b-fe3b-4a1e-b3ac-18484b2e4a60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>  Riwayat </value>
      <webElementGuid>66ff1019-9884-4241-a747-0bf0bc77e763</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DataTables_Table_0&quot;)/tbody[1]/tr[@class=&quot;odd&quot;]/td[@class=&quot;text-center&quot;]/div[@class=&quot;btn btn-info btn-sm&quot;]</value>
      <webElementGuid>26ade21d-1231-40b7-9e2c-6ff943beac3f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@onclick=&quot;lihatRiwayat('8455e158-1909-4009-a1b9-1decbf28fd09')&quot;]</value>
      <webElementGuid>f8a5577b-82fb-420f-8b82-56c6057c01ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='DataTables_Table_0']/tbody/tr/td[2]/div</value>
      <webElementGuid>00393686-3fba-48ef-8828-3d97cbb99098</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Aksi'])[2]/following::div[1]</value>
      <webElementGuid>680f874b-0faa-4031-9414-11be07911840</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dokumen'])[2]/following::div[2]</value>
      <webElementGuid>e62be8ce-3e57-4af1-9430-d7a45893eabd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='kewajiban 2'])[1]/preceding::div[1]</value>
      <webElementGuid>8fde4b96-0c18-4c7f-8554-0fbaa372fc89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bulanan'])[1]/preceding::div[1]</value>
      <webElementGuid>38d90353-1c7f-4326-8aeb-0d3de1023985</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Riwayat']/parent::*</value>
      <webElementGuid>54568d0a-82b3-44a2-aa0d-2a83c182d674</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/div</value>
      <webElementGuid>0fdca0cc-10c1-45c5-8fa3-693abd40f7f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '  Riwayat ' or . = '  Riwayat ')]</value>
      <webElementGuid>05088693-338b-4ba2-8c18-5e18f329470b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
