<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Disable</name>
   <tag></tag>
   <elementGuidId>6f96e9de-14f5-4d1a-82c2-fbf0104f9ced</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.btn.btn-danger.btn-sm</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[6]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=row[name=&quot;1 68111 Real Estat yang Dimiliki Sendiri atau Disewa ENABLE  Detail  Edit  Disable&quot;i] >> internal:role=button</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>47a214e4-412a-4bee-b464-a2f95323c764</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>539a3e60-019d-4fed-b068-dc4741616c9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-danger btn-sm</value>
      <webElementGuid>08207373-9a1e-427f-8378-12172de505e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>changeStatus('https://ocp-mmsgi.alfahuma.biz.id/master/kbli/eyJpdiI6InptMHBxRkIyd0pxQ0EzeXEreDBlQ3c9PSIsInZhbHVlIjoiTWZKeVl6NkR4T0Z4YlBDNWdlVTdCVWJrT2FzSmxYVXpUb3puTFRyWUdQSVM5Yi9WVThRWUZEYms4ZXFDK0UxVCIsIm1hYyI6IjYxNWJjOGNiNzNhODc5ZjQyYWU4ZWY5MTg5Y2Y3YzYxY2ZkOGZlOGY3ZjAwODA0ODAxODkxOGU4Zjg4YjQwZjQiLCJ0YWciOiIifQ==/DISABLE', $(this))</value>
      <webElementGuid>dff28695-81a0-4e59-a26b-76b0acb8cd9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-status</name>
      <type>Main</type>
      <value>ENABLE</value>
      <webElementGuid>0d4e3390-924d-484a-ace7-fb70e2a56839</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                             Disable
                        </value>
      <webElementGuid>1dd79a7d-e45c-4367-90bf-9a2eebf20f0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DataTables_Table_0&quot;)/tbody[1]/tr[@class=&quot;odd&quot;]/td[@class=&quot;text-center&quot;]/button[@class=&quot;btn btn-danger btn-sm&quot;]</value>
      <webElementGuid>3685e724-881e-4eea-aded-bc381b66a732</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[6]</value>
      <webElementGuid>fac5ab39-19c8-44e9-b434-cd4b4702ea86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='DataTables_Table_0']/tbody/tr/td[5]/button</value>
      <webElementGuid>b57ab3d7-b278-4292-96b1-34212728b84b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Penyiapan Lahan'])[1]/preceding::button[1]</value>
      <webElementGuid>0eb28fb2-7fce-4bc7-8bca-ae6e4641ba8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ENABLE'])[3]/preceding::button[1]</value>
      <webElementGuid>8d3a3e7b-56a2-4588-8267-66a68a3b05b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Disable']/parent::*</value>
      <webElementGuid>44ca6a7c-07d2-437d-8660-4f161d6869b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[5]/button</value>
      <webElementGuid>2406afbd-8099-46b5-a1a7-a0c638f91b66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = '
                             Disable
                        ' or . = '
                             Disable
                        ')]</value>
      <webElementGuid>978c71c3-8f17-4696-960c-aa1dd517d17d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
