<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_ProsesPerizinan_PerizinanBerakhir</name>
   <tag></tag>
   <elementGuidId>3247be21-3966-40b2-8e0c-6e3691f613b0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//h4[@id='counter-habis']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#counter-habis</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#counter-habis</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h4</value>
      <webElementGuid>0037674b-01d4-4854-ab4c-0a5035bc9869</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fw-bold text-danger</value>
      <webElementGuid>a7ccf798-e246-4d11-9ad5-b6d72ee45774</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>counter-habis</value>
      <webElementGuid>8df3c214-1ec3-48ba-83ef-b467f2304d69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>9e3699bd-ec12-4f5c-be8f-d379cc46382e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;counter-habis&quot;)</value>
      <webElementGuid>9c0a96d2-2885-4b90-9257-f2923b420b5f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//h4[@id='counter-habis']</value>
      <webElementGuid>0afe3a9b-a468-4850-8c79-0a20db61b82e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='layout-wrapper']/div[2]/div/div/div[2]/div/div[2]/div[3]/div/div/h4</value>
      <webElementGuid>b2217096-8e4c-49dd-bc85-17f128acc8c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MHU Coal'])[2]/following::h4[3]</value>
      <webElementGuid>1a0c611d-d5da-4a86-9025-0ff08b65acd7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Proses Perizinan'])[1]/following::h4[3]</value>
      <webElementGuid>a2b20c62-dd8e-40da-a474-e654f3a5548e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Perizinan Aktif'])[1]/preceding::h4[1]</value>
      <webElementGuid>9e9ea6e8-030c-4af4-b120-138a7558db0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Perizinan Lingkungan'])[1]/preceding::h4[2]</value>
      <webElementGuid>ccc8b757-7d2a-4f9b-9e0a-4840cc5dc1f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/h4</value>
      <webElementGuid>a438847a-f0df-43ee-a661-11f4cdc2f524</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h4[@id = 'counter-habis' and (text() = '6' or . = '6')]</value>
      <webElementGuid>5303a799-d4d0-45d4-a88c-669764578f01</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
