<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Permohonan</name>
   <tag></tag>
   <elementGuidId>8b7e2b4d-22dd-48cd-abc5-01a6bdcca518</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#topnav-67 > span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='topnav-67']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Permohonan&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>1dddbe94-a998-466f-9bd8-f5cd894ba0bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>key</name>
      <type>Main</type>
      <value>t-67</value>
      <webElementGuid>9eed3072-c067-448d-a663-dbc978f3fed6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Permohonan</value>
      <webElementGuid>396ebbf0-b10f-4a85-8421-c6e802313623</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;topnav-67&quot;)/span[1]</value>
      <webElementGuid>9887dbd6-7fd5-4eb9-a6be-46f670ebacf2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='topnav-67']/span</value>
      <webElementGuid>1ae09fb3-eb76-44db-85eb-234cbf92062d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Perizinan'])[1]/following::span[1]</value>
      <webElementGuid>ebcad77b-4516-4b4f-b5a4-0ea5b94657fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dashboard'])[1]/following::span[2]</value>
      <webElementGuid>09a829a4-ba38-49f2-ab66-a25e2f7e11d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Baru'])[1]/preceding::span[1]</value>
      <webElementGuid>aae1037c-b7f9-40f0-95c6-83260e35df6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Perpanjangan'])[1]/preceding::span[1]</value>
      <webElementGuid>ce48e589-0521-4b40-9fa9-48282d5ee12c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Permohonan']/parent::*</value>
      <webElementGuid>88d784a1-754f-4bb0-88c4-c4361487a3a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/div/div/a/span</value>
      <webElementGuid>315a743d-e191-40c3-9514-61e71c5375ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Permohonan' or . = 'Permohonan')]</value>
      <webElementGuid>895842b4-ad11-4b5f-8669-e930b37f49bb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
