<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>th_sorting_status</name>
   <tag></tag>
   <elementGuidId>eff5c1d5-d6d4-4805-85d5-0dbcfd55f621</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>th.text-center.sorting.sorting_desc</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='DataTables_Table_0_wrapper']/div[2]/div/div/div/div/table/thead/tr/th[12]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Status: activate to sort column ascending&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>th</value>
      <webElementGuid>f8b6a8d7-6bcf-4800-8aa9-4f2d880830bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-center sorting sorting_desc</value>
      <webElementGuid>ddf3031a-479b-4354-a97a-88034b3a4700</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>301c6bd6-18d2-4236-bc97-b18751ee798c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>DataTables_Table_0</value>
      <webElementGuid>1f03ace6-2139-4c6c-9734-515a9e2d734b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rowspan</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>0556d195-7c67-4477-bdb6-d1bc1251ac56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>colspan</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>27e05b82-b08f-4fea-8f3a-2712ff2346c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Status: activate to sort column ascending</value>
      <webElementGuid>054e6117-c65b-4828-8286-9dce98b50b4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-sort</name>
      <type>Main</type>
      <value>descending</value>
      <webElementGuid>597bc641-02ef-460f-bd86-feb7e03a61c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Status</value>
      <webElementGuid>cc4f8b01-d576-4150-8d0f-c6c249a30d5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DataTables_Table_0_wrapper&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-12&quot;]/div[@class=&quot;dataTables_scroll&quot;]/div[@class=&quot;dataTables_scrollHead&quot;]/div[@class=&quot;dataTables_scrollHeadInner&quot;]/table[@class=&quot;table table-bordered table-sm table-striped dt-responsive nowrap w-100 yajra-datatable mb-4 dataTable no-footer&quot;]/thead[@class=&quot;table-dark&quot;]/tr[1]/th[@class=&quot;text-center sorting sorting_desc&quot;]</value>
      <webElementGuid>17a20a95-75fb-43c1-b766-07c67ca71459</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='DataTables_Table_0_wrapper']/div[2]/div/div/div/div/table/thead/tr/th[12]</value>
      <webElementGuid>b2b9c53a-943e-4094-be27-e5690eeb2230</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tanggal Bayar'])[1]/following::th[1]</value>
      <webElementGuid>d26c223d-87b6-418f-9f07-338aad57e36d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='File Pembayaran'])[1]/following::th[2]</value>
      <webElementGuid>b4404757-1d3e-4e36-b0de-ba1bfb999f01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Aksi'])[1]/preceding::th[1]</value>
      <webElementGuid>fcb378f2-7e41-43c1-978a-a12b9afe8ef7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No'])[2]/preceding::th[2]</value>
      <webElementGuid>28e6ecfd-f56e-451a-b6aa-a58af95c9921</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Status']/parent::*</value>
      <webElementGuid>ada4f85d-ab8d-4b1d-a1eb-823481952008</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th[12]</value>
      <webElementGuid>64675659-3691-4477-a558-935d335fcbbc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//th[(text() = 'Status' or . = 'Status')]</value>
      <webElementGuid>52aa3d03-5ffb-4c89-8f27-6af6e5a0380a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
