<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_View-Detail_Testing Kewajiban Pembayaran</name>
   <tag></tag>
   <elementGuidId>270bdb2b-fad1-477c-b8e0-c27d43ea6ef5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.file-preview-link.btn.btn-success.btn-sm</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='DataTables_Table_0']/tbody/tr/td[8]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=row[name=&quot;1 P2025120004 MMS Group Indonesia Perdagangan dan Usaha Umum - ET utama 34029408329 Testing Kewajiban Pembayaran 10.000 Lihat 2026-01-09 - - Kewajiban Pembayaran Bukti Bayar&quot;i] >> internal:role=link</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>7057d9af-11d4-4711-85c4-716361ce7e86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>c2671881-d2b9-479e-a4ed-8239e5de6293</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>file-preview-link btn btn-success btn-sm</value>
      <webElementGuid>a9c87620-084f-459c-9d10-95ead4c494e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bs-toggle</name>
      <type>Main</type>
      <value>modal</value>
      <webElementGuid>137e165f-0040-4ba7-aa72-4425319f9542</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bs-target</name>
      <type>Main</type>
      <value>#previewModal</value>
      <webElementGuid>97ff9304-5f3e-4416-a44d-c50dd1f57bfe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-path</name>
      <type>Main</type>
      <value>/OCP/Permintaan Dana/P2025120004-019b2f86-8289-7091-bb6f-802932ca6e83.jpg</value>
      <webElementGuid>7a5273f0-2401-4a23-9319-6ecb7c8efbda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-download-url</name>
      <type>Main</type>
      <value>https://staging-ocp-lms.mmsgroup.co.id/owncloud/download?path=%2FOCP%2FPermintaan%20Dana%2FP2025120004-019b2f86-8289-7091-bb6f-802932ca6e83.jpg&amp;mode=download</value>
      <webElementGuid>28c4c1b2-f9b6-43f0-9dbc-913047b8b7f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Lihat</value>
      <webElementGuid>336e3e91-9b5c-4fae-8b33-4116a70c4952</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DataTables_Table_0&quot;)/tbody[1]/tr[@class=&quot;odd&quot;]/td[@class=&quot;text-center&quot;]/a[@class=&quot;file-preview-link btn btn-success btn-sm&quot;]</value>
      <webElementGuid>85940876-963d-48ed-87b1-76870599f8d7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='DataTables_Table_0']/tbody/tr/td[8]/a</value>
      <webElementGuid>a1b47a50-ef75-4688-9e9c-1806d50e9970</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Lihat')]</value>
      <webElementGuid>665e5ae1-6237-426e-8d46-72ab6ceb1e99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Testing Kewajiban Pembayaran'])[1]/following::a[1]</value>
      <webElementGuid>23f431b6-ea0d-4c33-9848-fed86f4b7125</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Perdagangan dan Usaha Umum - ET utama'])[1]/following::a[1]</value>
      <webElementGuid>8a2715b8-2cf8-4ee6-a3b6-084b6fc8df44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-'])[1]/preceding::a[1]</value>
      <webElementGuid>f596f01c-cc23-4176-b2f6-fe5458f56e68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-'])[2]/preceding::a[1]</value>
      <webElementGuid>80dd13b7-1a61-492d-896f-8a08a43bd741</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[5]</value>
      <webElementGuid>779bf368-0e79-4519-aae7-fd4c6f5e6caa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[8]/a</value>
      <webElementGuid>1510dd0e-2e9b-4008-ba8d-6ee0467a12d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and (text() = 'Lihat' or . = 'Lihat')]</value>
      <webElementGuid>77aa124a-e5ab-4038-8dcb-75a2462e910f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
