<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_View-Bukti-Bayar</name>
   <tag></tag>
   <elementGuidId>ae14676a-c310-4574-8f31-691432ef8c38</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.btn.btn-info.btn-sm.m-1.btn-bukti-bayar</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[8]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=row[name=&quot;1 P2025120004 MMS Group Indonesia Perdagangan dan Usaha Umum - ET utama 34029408329 Testing Kewajiban Pembayaran 10.000 Lihat 2026-01-09 - - Kewajiban Pembayaran Bukti Bayar&quot;i] >> internal:role=button</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>1f871c29-ffc7-4e6f-8c6d-06db09a568f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>4b823ec5-78d3-4293-9bd9-9ce0db359f05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-info btn-sm m-1 btn-bukti-bayar</value>
      <webElementGuid>9d741290-a33c-441d-8eca-7149c02a2980</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>019ba0fc-3d4e-7373-ab94-b22e47554380</value>
      <webElementGuid>fb743612-97d9-4d40-99ec-1ee85994070c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-izin</name>
      <type>Main</type>
      <value>P2025120004 - Perdagangan dan Usaha Umum - ET utama</value>
      <webElementGuid>47f615cf-591d-4a24-aecd-fdd106ff5959</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-kode</name>
      <type>Main</type>
      <value>34029408329</value>
      <webElementGuid>26ca9d3b-64a2-4e29-ab21-21d3cddff489</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-nama</name>
      <type>Main</type>
      <value>Testing Kewajiban Pembayaran</value>
      <webElementGuid>a96d801d-fe6f-4707-942d-758de504b1a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-nominal</name>
      <type>Main</type>
      <value>10.000</value>
      <webElementGuid>7e73d2a4-6a2e-4c5e-b04b-8125848f7963</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-request</name>
      <type>Main</type>
      <value>09-01-2026</value>
      <webElementGuid>14d07057-065a-4f65-aa6c-ee3df83b313d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-jatuhtempo</name>
      <type>Main</type>
      <value>09-01-2026</value>
      <webElementGuid>521bf659-5183-49a7-98a0-4964868a6bf1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bukti</name>
      <type>Main</type>
      <value>/OCP/Permintaan Dana/P2025120004-019b2f86-8289-7091-bb6f-802932ca6e83.jpg</value>
      <webElementGuid>a5aae5bc-61d0-448e-99db-aaedfe08e985</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-buktidownloadurl</name>
      <type>Main</type>
      <value>https://staging-ocp-lms.mmsgroup.co.id/owncloud/download?path=%2FOCP%2FPermintaan%20Dana%2FP2025120004-019b2f86-8289-7091-bb6f-802932ca6e83.jpg&amp;mode=download&amp;mode=download</value>
      <webElementGuid>3f94d4f1-c0b8-4af2-9d5b-8ef250194719</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-paymentfiledownload</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>9b05feb4-9c3c-4477-8671-bf3b59a7ae46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-dokumen</name>
      <type>Main</type>
      <value>[]</value>
      <webElementGuid>05c720ca-ff3d-47c1-997a-c9db249cb30d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-keterangan</name>
      <type>Main</type>
      <value>Testing</value>
      <webElementGuid>d47ae1ff-995e-49cc-af0d-15362f772cc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                    Bukti Bayar
                </value>
      <webElementGuid>7141cd21-82de-4d14-80ff-116d670b6e7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DataTables_Table_0&quot;)/tbody[1]/tr[@class=&quot;odd&quot;]/td[@class=&quot;text-center&quot;]/button[@class=&quot;btn btn-info btn-sm m-1 btn-bukti-bayar&quot;]</value>
      <webElementGuid>1b015c08-305d-4187-9b84-e899fcc55235</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[8]</value>
      <webElementGuid>d4896546-27f2-4135-908d-9b92cb5ecd50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='DataTables_Table_0']/tbody/tr/td[13]/button</value>
      <webElementGuid>74326dce-f7e0-4c74-b6f6-1ff2748f7557</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kewajiban Pembayaran'])[4]/following::button[1]</value>
      <webElementGuid>73a66523-7ff3-4783-8875-006ef0260cb4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-'])[2]/following::button[1]</value>
      <webElementGuid>ce6e368d-af67-4e21-b8f4-acaf840070fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='P2025120004'])[2]/preceding::button[1]</value>
      <webElementGuid>90b37f6a-84ac-4ffa-9149-b73ee1111db5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MMS Group Indonesia'])[3]/preceding::button[1]</value>
      <webElementGuid>686494a8-5f18-4098-804c-436bd06b201f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Bukti Bayar']/parent::*</value>
      <webElementGuid>273ad312-8aa4-4160-b7e4-a962a759fd58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[13]/button</value>
      <webElementGuid>d740d5b8-86ed-432c-a948-1d2efe94145f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = '
                    Bukti Bayar
                ' or . = '
                    Bukti Bayar
                ')]</value>
      <webElementGuid>fc8acae4-e5b1-43d1-9cc3-b0d499a7c50e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
