<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Bukti Bayar</name>
   <tag></tag>
   <elementGuidId>49c4ec95-de21-4d2d-99d2-07709c5d2f75</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.btn.btn-info.btn-sm.m-1.btn-bukti-bayar</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[8]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Bukti Bayar&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e9bea1c4-3aed-4a05-9fc8-97ee10ce6065</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3f7d22b9-f116-4cc4-bc19-d7774dfe611b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-info btn-sm m-1 btn-bukti-bayar</value>
      <webElementGuid>63c4ed49-9910-41ef-b286-7167f0bd5ffa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>019ba16b-6e52-707d-a555-c809e28747de</value>
      <webElementGuid>45ed00cc-b5ea-45b3-b8ca-ee81ef393842</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-izin</name>
      <type>Main</type>
      <value>P2025120004 - Perdagangan dan Usaha Umum - ET utama</value>
      <webElementGuid>8f61b3d8-369d-49a7-9090-82134cc09550</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-kode</name>
      <type>Main</type>
      <value>999999999</value>
      <webElementGuid>2e423fc9-c7b0-4864-bd06-a11123db7ed8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-nama</name>
      <type>Main</type>
      <value>Testing kewajiban pembayaran 2</value>
      <webElementGuid>b79fd8da-d238-4e42-bb2c-f7f8b16cae67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-nominal</name>
      <type>Main</type>
      <value>99.999</value>
      <webElementGuid>64e27dda-8dab-4574-9c8b-dd12df1312e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-request</name>
      <type>Main</type>
      <value>09-01-2026</value>
      <webElementGuid>fc293044-9e62-4c4b-af19-e2e054efb171</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-jatuhtempo</name>
      <type>Main</type>
      <value>30-06-2026</value>
      <webElementGuid>d56cc754-b600-4834-aaa6-147cc131a776</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bukti</name>
      <type>Main</type>
      <value>/OCP/Permintaan Dana/P2025120004-019b2f86-8289-7091-bb6f-802932ca6e83.png</value>
      <webElementGuid>963b1447-ec34-4fa0-a63e-db2e5097bbb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-buktidownloadurl</name>
      <type>Main</type>
      <value>https://staging-ocp-lms.mmsgroup.co.id/owncloud/download?path=%2FOCP%2FPermintaan%20Dana%2FP2025120004-019b2f86-8289-7091-bb6f-802932ca6e83.png&amp;mode=download&amp;mode=download</value>
      <webElementGuid>7d619cc3-9bcb-4903-a566-fd58920fed1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-paymentfiledownload</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>a99e4fa7-02ef-4e59-863c-342e31806a33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-dokumen</name>
      <type>Main</type>
      <value>[]</value>
      <webElementGuid>c66439d0-b70a-49ba-a0aa-2e719e0c97e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-keterangan</name>
      <type>Main</type>
      <value>Testing</value>
      <webElementGuid>9dfe1e3a-cae1-4a3f-8572-add8ea633af9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                    Bukti Bayar
                </value>
      <webElementGuid>e918127a-79b3-4591-bd92-f6343b6b0dd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DataTables_Table_0&quot;)/tbody[1]/tr[@class=&quot;odd&quot;]/td[@class=&quot;text-center&quot;]/button[@class=&quot;btn btn-info btn-sm m-1 btn-bukti-bayar&quot;]</value>
      <webElementGuid>5830985f-aa63-40af-bfd4-0d32957a61fb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[8]</value>
      <webElementGuid>f8362cd9-721b-4363-9aab-7a5bc3f81544</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='DataTables_Table_0']/tbody/tr/td[13]/button</value>
      <webElementGuid>b932fbf8-f78a-4c32-88ff-bbfcc85a77cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kewajiban Pembayaran'])[4]/following::button[1]</value>
      <webElementGuid>50f74c4f-7d17-4109-bcd3-273e75bd75c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-'])[2]/following::button[1]</value>
      <webElementGuid>c74584e6-72a3-40a4-ac1d-a8d6b16d1cf1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Menampilkan data ke 1 sampai 1 dari 1 total data. (filtered from 3 total entries)'])[1]/preceding::button[1]</value>
      <webElementGuid>ea359624-e172-4d8e-b82d-217d8c50cac9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sebelumnya'])[1]/preceding::button[1]</value>
      <webElementGuid>3c9dfeef-4877-450f-9b66-a096508fce8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Bukti Bayar']/parent::*</value>
      <webElementGuid>d56c5112-756f-4240-a5fe-5273588784c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[13]/button</value>
      <webElementGuid>19daddbe-f42c-4712-b325-9333dc004f3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = '
                    Bukti Bayar
                ' or . = '
                    Bukti Bayar
                ')]</value>
      <webElementGuid>91145b49-cdb1-4878-a2c9-0e5a49d01f97</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
