<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Kode Billing_permitfundscodebilling</name>
   <tag></tag>
   <elementGuidId>13979ae7-c308-4396-946a-a63e36102e51</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#permitfundscodebilling</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='permitfundscodebilling']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#permitfundscodebilling</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>868e6ec0-a5e5-4e83-b152-74f9a973e696</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6fb1b0ce-b8a3-4823-b24c-458bdf3a2c3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>c380f4a5-629a-4273-bb85-af7131cbd931</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>permitfundscodebilling</value>
      <webElementGuid>f741824b-92d6-4b8c-ae7c-0e6b7f49c302</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>permitfundscodebilling</value>
      <webElementGuid>76ff2c00-e951-4a8e-b534-f8911c010eb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;permitfundscodebilling&quot;)</value>
      <webElementGuid>dadee336-03c2-45b0-8393-7c7500c42b4e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='permitfundscodebilling']</value>
      <webElementGuid>b28d46ee-f33c-491e-b757-fb9063a36d10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modalContentPermintaanDana']/div[4]/div[2]/input</value>
      <webElementGuid>355452ed-d65f-451e-afea-c9e7136b0b41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>f259e7eb-d0b1-4118-bc04-85ce814b6911</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'permitfundscodebilling' and @id = 'permitfundscodebilling']</value>
      <webElementGuid>3b6328a9-c3f6-4dbd-b933-42f4ffe7690a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
