<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Tanggal Jatuh Tempo</name>
   <tag></tag>
   <elementGuidId>70a34295-3d4b-458e-afb7-0239f26181bb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#permitfundsduedate</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='permitfundsduedate']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#permitfundsduedate</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b7b8a403-604e-4834-94e5-b6e7de2bafa6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>date</value>
      <webElementGuid>8988cbe0-50d6-4a55-b21f-1109a43f7945</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>4250de1a-4794-43b6-8c6e-e25802535b1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>permitfundsduedate</value>
      <webElementGuid>326dcac1-c0ac-4aa4-835b-f52774a24d41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>permitfundsduedate</value>
      <webElementGuid>b3c79c77-46ea-4426-94f4-3102c3542214</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;permitfundsduedate&quot;)</value>
      <webElementGuid>996422c2-6aac-4fc3-aeeb-d99e094fcc9a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='permitfundsduedate']</value>
      <webElementGuid>961e43fa-2f31-4529-af23-bdbaf72adca9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modalContentPermintaanDana']/div[7]/div[2]/input</value>
      <webElementGuid>236ac6ac-c78f-4483-b4c1-37f43fe11ff8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div[2]/input</value>
      <webElementGuid>1a96ffad-d5b0-4878-a983-507d2dd52405</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'date' and @name = 'permitfundsduedate' and @id = 'permitfundsduedate']</value>
      <webElementGuid>473f2725-559c-4d5e-9ab2-9d825bc879fa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
