<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nama Billing_permitfundsnamebilling</name>
   <tag></tag>
   <elementGuidId>a5c0f10d-a6ff-44f7-828d-2b8004545dbf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#permitfundsnamebilling</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='permitfundsnamebilling']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#permitfundsnamebilling</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4c341d22-2c8e-462e-be67-891d6cbe2528</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5fdd9c93-bf4c-4e5e-a8ac-51f307ed50fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>e411a638-d7de-4954-984d-a2b940cd483e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>permitfundsnamebilling</value>
      <webElementGuid>aaf890a4-b663-49c0-9642-a8b4fa5113de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>permitfundsnamebilling</value>
      <webElementGuid>f31df9eb-2921-4051-8b0b-073a6a8d1281</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;permitfundsnamebilling&quot;)</value>
      <webElementGuid>7b01ec92-1fee-42d5-ada0-dd8c189ea23a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='permitfundsnamebilling']</value>
      <webElementGuid>29209912-8eab-4ac0-9266-f372e5a13e5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modalContentPermintaanDana']/div[5]/div[2]/input</value>
      <webElementGuid>679e6897-f143-43de-9193-14438f591153</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[2]/input</value>
      <webElementGuid>b50da724-b228-4314-a32c-5589a54bdba3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'permitfundsnamebilling' and @id = 'permitfundsnamebilling']</value>
      <webElementGuid>da6e3d84-0dc0-4fa1-824d-6596402d2ec9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
