<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Rencana</name>
   <tag></tag>
   <elementGuidId>05a7d414-5a21-4a7d-ac1c-ab935d059d80</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#filter-plan</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='filter-plan']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Rencana&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>c255c114-4d76-4194-bebe-eae33c31ca64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-select form-filter</value>
      <webElementGuid>cdb7000b-8245-4665-a55f-b98cd37cd2ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>filter-plan</value>
      <webElementGuid>3f785839-40c2-4ce2-a95f-e87db3fe611a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>filter[rep.plan]</value>
      <webElementGuid>1117978a-d8fd-4123-bd71-92c392c4ae2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                        --- Pilih ---
                                                                                    Q1
                                                                                    Q2
                                                                                    Q3
                                                                                    Q4
                                                                            </value>
      <webElementGuid>7aab4896-405a-49ea-95ae-70223f30254b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;filter-plan&quot;)</value>
      <webElementGuid>94e31876-f7f3-4090-98aa-03cefd8e90a5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='filter-plan']</value>
      <webElementGuid>a9c6a24b-3013-4954-a458-894f8c13fd90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='reporting-detail-content']/div/div/div/div/div/div[3]/div/select</value>
      <webElementGuid>b2c2a815-729b-4cbd-bcca-d5ce23a009d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rencana'])[1]/following::select[1]</value>
      <webElementGuid>358727ab-fce8-49e6-9320-afe91d873fed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Perusahaan'])[1]/following::select[2]</value>
      <webElementGuid>5974dbfe-68c1-4cc0-87f1-440350d2d989</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rencana (Tahun)'])[1]/preceding::select[1]</value>
      <webElementGuid>afb8fea2-8f82-4c5a-9de8-14db6c762a97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Status'])[1]/preceding::select[2]</value>
      <webElementGuid>6525b2c6-7195-41f9-8a83-2488c39ad5d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/select</value>
      <webElementGuid>37c68ffc-0d86-441f-bdb5-4bc69507e378</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'filter-plan' and @name = 'filter[rep.plan]' and (text() = '
                                        --- Pilih ---
                                                                                    Q1
                                                                                    Q2
                                                                                    Q3
                                                                                    Q4
                                                                            ' or . = '
                                        --- Pilih ---
                                                                                    Q1
                                                                                    Q2
                                                                                    Q3
                                                                                    Q4
                                                                            ')]</value>
      <webElementGuid>58d21515-44b2-4f1b-89cc-e15ae3a3e083</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
