<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Status</name>
   <tag></tag>
   <elementGuidId>6d8e4023-35ad-4664-8672-03726d67c799</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#filter-last_tracking_status</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='filter-last_tracking_status']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Status&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>e31284f6-8024-4055-b516-60473b59cc1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-select form-filter</value>
      <webElementGuid>ed595ac9-d94f-4b4c-8a2c-67c38980205a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>filter-last_tracking_status</value>
      <webElementGuid>d80f6063-33c1-4028-ba12-5b6895ff4277</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>filter[rep.last_tracking_status]</value>
      <webElementGuid>d9a19e8a-8738-4cdc-9ae4-f8c9e7134915</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                        --- Pilih ---
                                                                                    Proses
                                                                                    Terbit
                                                                            </value>
      <webElementGuid>189326c9-8061-4e0e-8c0c-1907b0111650</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;filter-last_tracking_status&quot;)</value>
      <webElementGuid>8101656f-1498-4782-87bb-0b900a3c77da</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='filter-last_tracking_status']</value>
      <webElementGuid>85c37f72-fa74-46d1-a852-f4f7d59fbbae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='reporting-detail-content']/div/div/div/div/div/div[5]/div/select</value>
      <webElementGuid>4dcd6cf0-409d-46b3-9b61-4a53c2df79d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Status'])[1]/following::select[1]</value>
      <webElementGuid>8caac33c-0e52-48a2-b00f-b7fc5e0c6415</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rencana (Tahun)'])[1]/following::select[2]</value>
      <webElementGuid>62ace211-99e6-4074-880c-9e49aebb04f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Daftar Laporan Perizinan'])[1]/preceding::select[1]</value>
      <webElementGuid>f7514570-e3b5-4362-84d2-ed4442f0fcb9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/select</value>
      <webElementGuid>33e2bd49-138e-407a-a2c2-b19090990f51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'filter-last_tracking_status' and @name = 'filter[rep.last_tracking_status]' and (text() = '
                                        --- Pilih ---
                                                                                    Proses
                                                                                    Terbit
                                                                            ' or . = '
                                        --- Pilih ---
                                                                                    Proses
                                                                                    Terbit
                                                                            ')]</value>
      <webElementGuid>3e6549be-28a5-48d8-843e-00ee4e13f7c1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
