<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Detail</name>
   <tag></tag>
   <elementGuidId>780734b8-2b3a-4a0d-9d57-243f4b2d9c05</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='DataTables_Table_0']/tbody/tr/td[6]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.btn.btn-info.btn-sm.m-1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot; Detail&quot;i] >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>747ea55b-ff9d-40aa-8c4a-8bef8afaf62f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://ocp-mmsgi.alfahuma.biz.id/master/category_permit/eyJpdiI6InVoRFF5U24xeTFTTDFJVVNnY0xWTkE9PSIsInZhbHVlIjoiZ3cxbnMvMnhpWFdaOFZUczdvdlJhcFJISjBGTGtMNDQ2cHB1SUI5WE9IK2psKzZXZXhiaEU2eDN3TisyY0NNSiIsIm1hYyI6IjdjNmQxMjg0MTNiYmEzN2U2NDhjNzE1NmZhMjE2OTk1MDUyYWJmODQxZDQ5OThhZGM1YzFlYjYwYTYyYWI0ODAiLCJ0YWciOiIifQ==</value>
      <webElementGuid>7dc1eb3c-fcce-4080-9e09-325c65e1ec4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-info btn-sm m-1</value>
      <webElementGuid>f5b31ecb-091c-4e3c-a7fc-df849336e5bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                         Detail
                    </value>
      <webElementGuid>fefe15b3-a4cf-4e3a-b796-546ff1d1aa3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DataTables_Table_0&quot;)/tbody[1]/tr[@class=&quot;odd&quot;]/td[@class=&quot;text-center&quot;]/a[@class=&quot;btn btn-info btn-sm m-1&quot;]</value>
      <webElementGuid>980a3008-04a7-49c4-9468-63cbd7887932</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='DataTables_Table_0']/tbody/tr/td[6]/a</value>
      <webElementGuid>caf8893a-42dd-4aab-8625-7bd760496a93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Real Estat yang Dimiliki Sendiri atau Disewa'])[2]/following::a[1]</value>
      <webElementGuid>eb7f72b9-1abc-4290-b743-43a572231b44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ENABLE'])[2]/following::a[1]</value>
      <webElementGuid>3c5f7745-9bbf-4d4b-84eb-f33bbec8e194</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Detail']/parent::*</value>
      <webElementGuid>178e2a8a-7fb8-47ac-a672-b82340b90d0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://ocp-mmsgi.alfahuma.biz.id/master/category_permit/eyJpdiI6InVoRFF5U24xeTFTTDFJVVNnY0xWTkE9PSIsInZhbHVlIjoiZ3cxbnMvMnhpWFdaOFZUczdvdlJhcFJISjBGTGtMNDQ2cHB1SUI5WE9IK2psKzZXZXhiaEU2eDN3TisyY0NNSiIsIm1hYyI6IjdjNmQxMjg0MTNiYmEzN2U2NDhjNzE1NmZhMjE2OTk1MDUyYWJmODQxZDQ5OThhZGM1YzFlYjYwYTYyYWI0ODAiLCJ0YWciOiIifQ==')]</value>
      <webElementGuid>0f1d6053-d38a-451c-9212-cb91eb85bd69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[6]/a</value>
      <webElementGuid>6b14a50d-63e0-4e75-ba82-56c5cc45957d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://ocp-mmsgi.alfahuma.biz.id/master/category_permit/eyJpdiI6InVoRFF5U24xeTFTTDFJVVNnY0xWTkE9PSIsInZhbHVlIjoiZ3cxbnMvMnhpWFdaOFZUczdvdlJhcFJISjBGTGtMNDQ2cHB1SUI5WE9IK2psKzZXZXhiaEU2eDN3TisyY0NNSiIsIm1hYyI6IjdjNmQxMjg0MTNiYmEzN2U2NDhjNzE1NmZhMjE2OTk1MDUyYWJmODQxZDQ5OThhZGM1YzFlYjYwYTYyYWI0ODAiLCJ0YWciOiIifQ==' and (text() = '
                         Detail
                    ' or . = '
                         Detail
                    ')]</value>
      <webElementGuid>d4b81bca-1b68-4da4-9565-4e9bccebe0b7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
