<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Edit</name>
   <tag></tag>
   <elementGuidId>c5265507-766c-4179-b4ee-ed261f21abb2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='DataTables_Table_0']/tbody/tr/td[6]/a[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.btn.btn-primary.btn-sm.m-1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot; Edit&quot;i] >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>2b2fd648-21f6-4bfb-abe5-d1bbebb924a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://ocp-mmsgi.alfahuma.biz.id/master/category_permit/eyJpdiI6InVoRFF5U24xeTFTTDFJVVNnY0xWTkE9PSIsInZhbHVlIjoiZ3cxbnMvMnhpWFdaOFZUczdvdlJhcFJISjBGTGtMNDQ2cHB1SUI5WE9IK2psKzZXZXhiaEU2eDN3TisyY0NNSiIsIm1hYyI6IjdjNmQxMjg0MTNiYmEzN2U2NDhjNzE1NmZhMjE2OTk1MDUyYWJmODQxZDQ5OThhZGM1YzFlYjYwYTYyYWI0ODAiLCJ0YWciOiIifQ==/edit</value>
      <webElementGuid>047deee2-07d8-48a2-960d-e69d05a9dea6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary btn-sm m-1</value>
      <webElementGuid>4f0c36be-23e3-4e90-8a2f-f284517768e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                             Edit
                        </value>
      <webElementGuid>57654c51-9f8f-4524-815c-f3731627c12b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DataTables_Table_0&quot;)/tbody[1]/tr[@class=&quot;odd&quot;]/td[@class=&quot;text-center&quot;]/a[@class=&quot;btn btn-primary btn-sm m-1&quot;]</value>
      <webElementGuid>bdb8ebb8-1465-4094-a737-0ad0b8a940d1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='DataTables_Table_0']/tbody/tr/td[6]/a[2]</value>
      <webElementGuid>a912b29f-1583-41f3-a9e9-b9b815462405</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Real Estat yang Dimiliki Sendiri atau Disewa'])[2]/following::a[2]</value>
      <webElementGuid>83f466f3-2ae0-463a-b768-4553bd8f1018</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Perizinan Lingkungan'])[1]/preceding::a[1]</value>
      <webElementGuid>71e804f4-19f2-4a56-a625-bf6e21b7b8c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Edit']/parent::*</value>
      <webElementGuid>103bcfd6-2694-40c2-a9f8-89aed959fc0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://ocp-mmsgi.alfahuma.biz.id/master/category_permit/eyJpdiI6InVoRFF5U24xeTFTTDFJVVNnY0xWTkE9PSIsInZhbHVlIjoiZ3cxbnMvMnhpWFdaOFZUczdvdlJhcFJISjBGTGtMNDQ2cHB1SUI5WE9IK2psKzZXZXhiaEU2eDN3TisyY0NNSiIsIm1hYyI6IjdjNmQxMjg0MTNiYmEzN2U2NDhjNzE1NmZhMjE2OTk1MDUyYWJmODQxZDQ5OThhZGM1YzFlYjYwYTYyYWI0ODAiLCJ0YWciOiIifQ==/edit')]</value>
      <webElementGuid>1f8d1c1b-1ddc-4076-afb1-3459c1392fb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[6]/a[2]</value>
      <webElementGuid>5711e87d-b83c-488e-ba9c-0223963feb81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://ocp-mmsgi.alfahuma.biz.id/master/category_permit/eyJpdiI6InVoRFF5U24xeTFTTDFJVVNnY0xWTkE9PSIsInZhbHVlIjoiZ3cxbnMvMnhpWFdaOFZUczdvdlJhcFJISjBGTGtMNDQ2cHB1SUI5WE9IK2psKzZXZXhiaEU2eDN3TisyY0NNSiIsIm1hYyI6IjdjNmQxMjg0MTNiYmEzN2U2NDhjNzE1NmZhMjE2OTk1MDUyYWJmODQxZDQ5OThhZGM1YzFlYjYwYTYyYWI0ODAiLCJ0YWciOiIifQ==/edit' and (text() = '
                             Edit
                        ' or . = '
                             Edit
                        ')]</value>
      <webElementGuid>81803576-c213-42c4-882c-0dff18426df9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
