<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_CategoryPermitDesc</name>
   <tag></tag>
   <elementGuidId>8a0fe697-ad2b-4fb2-89ea-67db15d70257</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='categorypermitdesc']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#categorypermitdesc</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Enter category permit desc&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>feed6c85-3ce2-4ebe-b00a-483e45c78be7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control </value>
      <webElementGuid>f180ca2b-e9dc-4325-90e9-1d483b0e336e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>categorypermitdesc</value>
      <webElementGuid>beebafc0-1f0d-457a-8dce-dc7fe1600888</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>categorypermitdesc</value>
      <webElementGuid>3af18b83-6b7f-4d4d-b022-0bf54bd0acd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>6d950ba9-8359-4776-a29f-342162e75307</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter category permit desc</value>
      <webElementGuid>37a875e0-33ce-453f-b84e-cece10fbb8d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Perizinan Usaha</value>
      <webElementGuid>14f351a2-bdb8-4fa9-af62-0d60a5e9b789</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;categorypermitdesc&quot;)</value>
      <webElementGuid>72c580de-a9c3-4e11-8e0a-7257a975072f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='categorypermitdesc']</value>
      <webElementGuid>aba887a2-b8d8-4751-a8e9-4aa305c410c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='layout-wrapper']/div[2]/div/div/div[2]/div/div/div/div/div/form/div[2]/textarea</value>
      <webElementGuid>471bc556-3eb0-4468-bddb-3f9e17b5439b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Category Permit Desc'])[1]/following::textarea[1]</value>
      <webElementGuid>dd309a4a-8bc1-4702-be73-75d608849b7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Category Permit Name'])[1]/following::textarea[1]</value>
      <webElementGuid>557130ef-a845-4126-b91a-1be09db85ca9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='KBLI'])[2]/preceding::textarea[1]</value>
      <webElementGuid>844ac156-784b-49d1-8516-0120b002c2f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Real Estat yang Dimiliki Sendiri atau Disewa'])[2]/preceding::textarea[1]</value>
      <webElementGuid>047c3ac4-e715-4396-a0b8-1119799822cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Perizinan Usaha']/parent::*</value>
      <webElementGuid>005abf0f-9925-4c8e-9809-351d345f57dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>792d91d5-6109-42f1-be19-9ad2561d38e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'categorypermitdesc' and @name = 'categorypermitdesc' and @placeholder = 'Enter category permit desc' and (text() = 'Perizinan Usaha' or . = 'Perizinan Usaha')]</value>
      <webElementGuid>1f372fe4-c599-449f-85f1-3d970fa1793b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
