<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nama Kategori Perizinan (ENG)_categorypermitnameeng</name>
   <tag></tag>
   <elementGuidId>aadf9f14-65e8-47c1-bfac-af819d7bf522</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='categorypermitnameeng']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#categorypermitnameeng</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Nama Kategori Perizinan (ENG)&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e71f9bc5-b92c-482a-b83a-52f2a40ae04e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>496eacc9-f8df-4a47-9b0b-d057ce13322a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control </value>
      <webElementGuid>95cccee3-58bc-4e91-864b-20c6d9c93ce6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>categorypermitnameeng</value>
      <webElementGuid>f2ad91fd-a321-4203-910b-f6e3a854a0b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>categorypermitnameeng</value>
      <webElementGuid>8d55863a-7419-49eb-a16d-a98d36e6d1f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan nama kategori perizinan</value>
      <webElementGuid>d2ed8486-65f1-402c-9d04-409c64bfb0c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;categorypermitnameeng&quot;)</value>
      <webElementGuid>045370bb-f60d-4f1e-abc9-d5ddb6648e06</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='categorypermitnameeng']</value>
      <webElementGuid>c8bb25f4-7307-4575-931d-f3b72b58ca7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='layout-wrapper']/div[2]/div/div/div[2]/div/div/div/div/div/form/div[2]/input</value>
      <webElementGuid>98b31d07-b233-43f6-8113-618f71943b5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>3bc213f9-891d-45e2-9d0d-4d7cc2aeda32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'categorypermitnameeng' and @name = 'categorypermitnameeng' and @placeholder = 'Masukkan nama kategori perizinan']</value>
      <webElementGuid>0fb0e0c5-d8be-465b-a931-7e1ab164bf0a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
