<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_JenisPerizinan-Aktif</name>
   <tag></tag>
   <elementGuidId>aa742d36-ebb6-4c92-befa-b3298849d21c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='apexchartsyhot5u5y']/div[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.apexcharts-toolbar</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#apexchartsyhot5u5y div >> internal:has-text=&quot;Download SVGDownload PNGDownload CSV&quot;i >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>dae45c09-5c45-43a9-ba9f-7b447f86b8e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>apexcharts-toolbar</value>
      <webElementGuid>ed7e75c4-37dd-4672-9ec5-0022cf2db6b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Download SVGDownload PNGDownload CSV</value>
      <webElementGuid>c06ca718-af11-4c08-b329-5a0224780e52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;apexchartsyhot5u5y&quot;)/div[@class=&quot;apexcharts-toolbar&quot;]</value>
      <webElementGuid>41ff9a8b-88ce-4c8d-bd03-59f2633aa7ef</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='apexchartsyhot5u5y']/div[3]</value>
      <webElementGuid>7db2d025-274b-4636-9e17-ea2773fc92ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jenis Perizinan:'])[1]/following::div[5]</value>
      <webElementGuid>948e9547-f59c-4272-b50b-417d7347313d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Perizinan Usaha'])[3]/following::div[8]</value>
      <webElementGuid>8b725adf-4e22-4da4-a570-089719c01a93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[3]/div/div/div[3]</value>
      <webElementGuid>39295dea-f536-4f50-82f6-7fb28d86569b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Download SVGDownload PNGDownload CSV' or . = 'Download SVGDownload PNGDownload CSV')]</value>
      <webElementGuid>03a89287-c3e1-4cee-82c0-6954890e0f87</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
