<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Download-Perizinan-utama</name>
   <tag></tag>
   <elementGuidId>07d914d6-df92-43d9-8a17-aea4da46508b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='DataTables_Table_0']/tbody/tr/td[7]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.btn.btn-success.btn-sm</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=row[name=&quot;MHU Coal Perizinan Lingkungan - Pengelolaan Limbah 23456 2025-10-30 2025-10-10 Menteri Energi dan Sumber Daya Mineral  Download&quot;i] >> internal:role=link</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>9933684b-38c2-403e-8956-7afec182289b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://ocp-mmsgi.alfahuma.biz.id/owncloud/download?path=%2FOCP%2FPerizinan%2FP2025100001%2F0199c0e5-c2e6-71e6-adec-8d32e35c5478%2FTracking%2FTrackingDisetujui.png&amp;mode=download</value>
      <webElementGuid>55f02f48-debe-4275-981d-3ba2c628386a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-success btn-sm</value>
      <webElementGuid>b8ca263c-d58b-44fa-b759-3894d17bb6dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>2aa3971f-81d9-4080-b042-1a84246781c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rel</name>
      <type>Main</type>
      <value>noopener noreferrer</value>
      <webElementGuid>30dd4c53-05af-4013-8a21-4c61444fb99a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Download</value>
      <webElementGuid>17cf6c9d-3b7d-4595-bfbd-d6a9eb7506c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DataTables_Table_0&quot;)/tbody[1]/tr[@class=&quot;odd&quot;]/td[@class=&quot;text-center&quot;]/a[@class=&quot;btn btn-success btn-sm&quot;]</value>
      <webElementGuid>3e1dc4d8-0707-41a6-a13d-fb103a33f62d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='DataTables_Table_0']/tbody/tr/td[7]/a</value>
      <webElementGuid>ca77df07-d024-47dd-a6d1-91fb096b0b21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Download')]</value>
      <webElementGuid>ce0486f0-0d38-4e9d-8690-23d4f2f2e3e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Menteri Energi dan Sumber Daya Mineral'])[1]/following::a[1]</value>
      <webElementGuid>006304a8-4260-4097-8a30-c65aee9c65b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Perizinan Lingkungan - Pengelolaan Limbah'])[1]/following::a[1]</value>
      <webElementGuid>ac5215b9-61e6-4025-ac4b-41978e0c4071</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Menampilkan data ke 1 sampai 1 dari 1 total data.'])[1]/preceding::a[1]</value>
      <webElementGuid>dee25833-b0ed-4299-a62b-90f30e860746</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sebelumnya'])[1]/preceding::a[1]</value>
      <webElementGuid>3f073f3c-86fc-47dd-8b80-f7deba984077</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Download']/parent::*</value>
      <webElementGuid>6011de31-2e75-4d5c-a626-439f78d8b6e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://ocp-mmsgi.alfahuma.biz.id/owncloud/download?path=%2FOCP%2FPerizinan%2FP2025100001%2F0199c0e5-c2e6-71e6-adec-8d32e35c5478%2FTracking%2FTrackingDisetujui.png&amp;mode=download')]</value>
      <webElementGuid>01bb73d6-fb80-43d4-966a-4452db8822c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[7]/a</value>
      <webElementGuid>067ebb14-9cef-4c1d-9f1b-7312460b3756</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://ocp-mmsgi.alfahuma.biz.id/owncloud/download?path=%2FOCP%2FPerizinan%2FP2025100001%2F0199c0e5-c2e6-71e6-adec-8d32e35c5478%2FTracking%2FTrackingDisetujui.png&amp;mode=download' and (text() = ' Download' or . = ' Download')]</value>
      <webElementGuid>d16953e3-440a-4e03-9834-4e3371a7758e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
