<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_DataTables</name>
   <tag></tag>
   <elementGuidId>fbaa37f6-8a89-422e-9284-ea489ec785c4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@name='DataTables_Table_0_length']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;DataTables_Table_0_length&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>select[name=&quot;DataTables_Table_0_length&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>531a97c5-14e2-49c1-bf17-70b737f48275</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>DataTables_Table_0_length</value>
      <webElementGuid>131e99db-c81c-4c53-aca1-435f5672601c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>DataTables_Table_0</value>
      <webElementGuid>0ce18b48-af21-4546-b31f-3cc797b1e7f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>custom-select custom-select-sm form-control form-control-sm</value>
      <webElementGuid>7438c6b0-5962-4f71-93c3-4627c5e76e33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>102550100</value>
      <webElementGuid>579baeb5-4f65-4de4-947d-76add4da5413</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DataTables_Table_0_length&quot;)/label[1]/select[@class=&quot;custom-select custom-select-sm form-control form-control-sm&quot;]</value>
      <webElementGuid>3cddb549-960e-4726-bedb-6765e20a92ee</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='DataTables_Table_0_length']</value>
      <webElementGuid>8aa03c87-131b-4325-8dc8-30cc6a22f66d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='DataTables_Table_0_length']/label/select</value>
      <webElementGuid>922b8012-bc8a-400d-ad41-7ae17315d6f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Perizinan Utama'])[1]/following::select[1]</value>
      <webElementGuid>2957128c-ffdf-4fc5-82b3-32e55a4ef7de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cari :'])[1]/preceding::select[1]</value>
      <webElementGuid>003b77f6-c037-4ece-ab49-57ff29cca5e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nama Entitas'])[1]/preceding::select[1]</value>
      <webElementGuid>ac08ca81-1bf0-46e4-ba0c-3ac50a79af5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/select</value>
      <webElementGuid>5bfd3b99-7d5e-4587-993e-d78b38ce0c57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'DataTables_Table_0_length' and (text() = '102550100' or . = '102550100')]</value>
      <webElementGuid>771e0d05-e2fe-43ca-8780-8b989d9859d7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
