<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Pilih-Company</name>
   <tag></tag>
   <elementGuidId>41cb28aa-633b-4576-bf86-28e0644ba82e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#select2-companyid-dr-container</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-companyid-dr-container']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#select2-companyid-dr-container</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>dd794902-be52-4730-ac02-0d97da7c6ec4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>5644c04f-fc8a-4c0a-b9e7-685c72a8fa76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-companyid-dr-container</value>
      <webElementGuid>82a5cf4c-5d53-4dcc-98c5-7fb126446c07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>17c8733f-4a93-454f-a60a-f59d9d611b04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>fa7ae9bd-bdae-4308-ac45-a59465489094</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>-- Pilih --</value>
      <webElementGuid>b10db90b-4e03-4554-9c92-4f414f281c58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>-- Pilih --</value>
      <webElementGuid>9f24e647-7386-4d0a-8ee0-61f49d89d351</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-companyid-dr-container&quot;)</value>
      <webElementGuid>f5a06aff-17f9-47ef-a652-d7c52fd5bd21</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-companyid-dr-container']</value>
      <webElementGuid>4818fba8-8646-423c-8c9d-b62be047a553</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form-permohonan-baru']/div/div/span/span/span/span</value>
      <webElementGuid>37d51d68-34f5-4dd6-829a-7ba0a1bfa097</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pilih Company'])[1]/following::span[4]</value>
      <webElementGuid>3f0eeec7-1c9a-477c-a6ef-071251d2177a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Permohonan Baru'])[1]/following::span[4]</value>
      <webElementGuid>fb15d06b-6723-463b-9f52-942100c49ba2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[1]/preceding::span[3]</value>
      <webElementGuid>d26eea0d-ff08-40a0-84fc-e9bff2d34f2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span/span/span</value>
      <webElementGuid>ec5a7568-7a5f-4bdd-9939-62a5f057c71d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-companyid-dr-container' and @title = '-- Pilih --' and (text() = '-- Pilih --' or . = '-- Pilih --')]</value>
      <webElementGuid>6c9596ed-e09a-4a4e-851b-2a97326744ab</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
