<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Keterangan</name>
   <tag></tag>
   <elementGuidId>816f41e3-39b7-4db0-ae89-14261970a7f2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#subpermittrackingdesc</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='subpermittrackingdesc']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#subpermittrackingdesc</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>0d40587b-f003-459e-a278-86e38f67b123</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>98cc9458-2e6f-4b1f-9daa-4ff837f55360</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>14de2ed5-35bc-4a3d-9b20-3451e10b9a43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>subpermittrackingdesc</value>
      <webElementGuid>d7f4008a-5283-4f02-a85a-aad00b1f80ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>subpermittrackingdesc</value>
      <webElementGuid>3e366d97-75c3-40c6-8ef1-7a8e15bc5468</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;subpermittrackingdesc&quot;)</value>
      <webElementGuid>b837920e-4355-42ae-b5e8-07ad3a19c6c1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='subpermittrackingdesc']</value>
      <webElementGuid>748fa89a-7428-4cd6-8af5-10019cb47f6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formData']/div[2]/div[2]/textarea</value>
      <webElementGuid>0cdfe49b-53a8-4d9a-b167-4e9776aada03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>d453441d-7575-42c7-a04e-6e78f56c12df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'subpermittrackingdesc' and @id = 'subpermittrackingdesc']</value>
      <webElementGuid>d5142957-eaed-4ce8-95ee-6e701c8283b0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
