<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nama KBLI (ENG)_kblinameeng</name>
   <tag></tag>
   <elementGuidId>0cdc6c1e-1822-4ab9-8c4b-fac8a0b3fbe5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#kblinameeng</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='kblinameeng']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Nama KBLI (ENG)&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d4c7baf3-e7fe-4f82-bccd-ca8db225adae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>fec0a1bb-8160-45b2-b111-70805c3e9b1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control </value>
      <webElementGuid>6f7ec94e-ab88-44ff-9364-1b76998537f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>kblinameeng</value>
      <webElementGuid>1b393c80-b7f0-4204-a306-b7a6915cb34b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>kblinameeng</value>
      <webElementGuid>9ecb0c2f-1f79-45c3-b4d0-a6dda5e3e499</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan nama KBLI</value>
      <webElementGuid>ed57f5ac-352c-4526-9e38-16017ce7d425</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;kblinameeng&quot;)</value>
      <webElementGuid>ed58ccc1-0966-49df-a4aa-b0596ac95a6f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='kblinameeng']</value>
      <webElementGuid>89255d68-74c5-4b6e-84ea-f6483fbe293e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='layout-wrapper']/div[2]/div/div/div[2]/div/div/div/div/div/form/div[3]/input</value>
      <webElementGuid>86034a80-74e2-415c-b1fb-431ed936c128</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>b40e81c5-f572-4bea-8e4e-9eb7e91463e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'kblinameeng' and @name = 'kblinameeng' and @placeholder = 'Masukkan nama KBLI']</value>
      <webElementGuid>22de6d53-ea5d-44d3-974a-73ac81374b2f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
