<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Edit</name>
   <tag></tag>
   <elementGuidId>553df4f9-3d4e-4522-b95d-7771272481f9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='DataTables_Table_0']/tbody/tr/td[7]/a[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.btn.btn-primary.btn-sm.m-1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot; Edit&quot;i] >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>70ffb759-0882-450d-9e6a-fb78634a5aa2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://ocp-mmsgi.alfahuma.biz.id/master/type_permit/eyJpdiI6ImprVEYxZHdrSTNCQlIxMVVuWUlnQmc9PSIsInZhbHVlIjoiOWVzcE5wSVYyZDFzUVpnbExhVlNqOGNjbFgvY29vVWJwUi9XY3o1d2JTR3Qyd3pHQTZmTFN6V2xJNEZmRUZpQyIsIm1hYyI6ImYyYTAzNGJjNzBjMWI0YjY5YTkzMWExMTQ3Yzg2MzJiMWUxZmE0NWZmM2FiYzdiZDFjNmRkYWNkY2E0MDU4NjEiLCJ0YWciOiIifQ==/edit</value>
      <webElementGuid>86e039ab-0a87-47ea-aa89-dd88a26260ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary btn-sm m-1</value>
      <webElementGuid>47b48725-3471-4939-919f-876cd765862a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                             Edit
                        </value>
      <webElementGuid>3dfe0414-3db5-42dd-b495-f64f37a6a239</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DataTables_Table_0&quot;)/tbody[1]/tr[@class=&quot;odd&quot;]/td[@class=&quot;text-center&quot;]/a[@class=&quot;btn btn-primary btn-sm m-1&quot;]</value>
      <webElementGuid>72453540-0adb-489b-af25-71f66bdc7efe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='DataTables_Table_0']/tbody/tr/td[7]/a[2]</value>
      <webElementGuid>76be2a8b-9610-4f3a-b5ed-abbe954920f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ENABLE'])[2]/following::a[2]</value>
      <webElementGuid>66da4cd4-803d-4342-88be-a0de1d488fb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Persetujuan Teknis Pengelolaan Limbah Bahan Berbahaya dan Beracun'])[1]/preceding::a[1]</value>
      <webElementGuid>5ea340df-05f6-4707-85f8-ca0741d4444c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Edit']/parent::*</value>
      <webElementGuid>73ab0a37-6641-47e8-b691-58e9349aa708</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://ocp-mmsgi.alfahuma.biz.id/master/type_permit/eyJpdiI6ImprVEYxZHdrSTNCQlIxMVVuWUlnQmc9PSIsInZhbHVlIjoiOWVzcE5wSVYyZDFzUVpnbExhVlNqOGNjbFgvY29vVWJwUi9XY3o1d2JTR3Qyd3pHQTZmTFN6V2xJNEZmRUZpQyIsIm1hYyI6ImYyYTAzNGJjNzBjMWI0YjY5YTkzMWExMTQ3Yzg2MzJiMWUxZmE0NWZmM2FiYzdiZDFjNmRkYWNkY2E0MDU4NjEiLCJ0YWciOiIifQ==/edit')]</value>
      <webElementGuid>c3c0d6db-555c-4f0a-aed6-1cba973639fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[7]/a[2]</value>
      <webElementGuid>72927622-df4c-42da-aefc-165b35aa7e24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://ocp-mmsgi.alfahuma.biz.id/master/type_permit/eyJpdiI6ImprVEYxZHdrSTNCQlIxMVVuWUlnQmc9PSIsInZhbHVlIjoiOWVzcE5wSVYyZDFzUVpnbExhVlNqOGNjbFgvY29vVWJwUi9XY3o1d2JTR3Qyd3pHQTZmTFN6V2xJNEZmRUZpQyIsIm1hYyI6ImYyYTAzNGJjNzBjMWI0YjY5YTkzMWExMTQ3Yzg2MzJiMWUxZmE0NWZmM2FiYzdiZDFjNmRkYWNkY2E0MDU4NjEiLCJ0YWciOiIifQ==/edit' and (text() = '
                             Edit
                        ' or . = '
                             Edit
                        ')]</value>
      <webElementGuid>4a3ec62c-d123-4f36-b6fc-ce078b33f29e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
