<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Disable</name>
   <tag></tag>
   <elementGuidId>a44ef697-1a28-42c5-a5eb-eaa233e726e7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[6]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.btn.btn-danger.btn-sm</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=row[name=&quot;1 Sertifikat Standar OSS Sertifikat Standar OSS Perizinan Usaha Real Estat yang Dimiliki Sendiri atau Disewa ENABLE  Detail  Edit  Disable&quot;i] >> internal:role=button</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>73233392-5af9-41bf-842c-36fb2e1515fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a9b48858-e518-4a74-8fea-f686b53cbf81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-danger btn-sm</value>
      <webElementGuid>1fa07d07-5dc2-416f-9bfc-119fe181aab4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>changeStatus('https://ocp-mmsgi.alfahuma.biz.id/master/type_permit/eyJpdiI6ImprVEYxZHdrSTNCQlIxMVVuWUlnQmc9PSIsInZhbHVlIjoiOWVzcE5wSVYyZDFzUVpnbExhVlNqOGNjbFgvY29vVWJwUi9XY3o1d2JTR3Qyd3pHQTZmTFN6V2xJNEZmRUZpQyIsIm1hYyI6ImYyYTAzNGJjNzBjMWI0YjY5YTkzMWExMTQ3Yzg2MzJiMWUxZmE0NWZmM2FiYzdiZDFjNmRkYWNkY2E0MDU4NjEiLCJ0YWciOiIifQ==/DISABLE', $(this))</value>
      <webElementGuid>aceb9ba4-f730-42d1-9da5-dfbf6dbe635a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-status</name>
      <type>Main</type>
      <value>ENABLE</value>
      <webElementGuid>df760e4e-43ee-46f6-936e-bdaebdd07c24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                             Disable
                        </value>
      <webElementGuid>fbf1c215-3a34-45c5-a4f3-5a6458cec194</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DataTables_Table_0&quot;)/tbody[1]/tr[@class=&quot;odd&quot;]/td[@class=&quot;text-center&quot;]/button[@class=&quot;btn btn-danger btn-sm&quot;]</value>
      <webElementGuid>3d82997e-cfac-4ed1-acdc-2fe9bea26a1b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[6]</value>
      <webElementGuid>81db897b-ff3f-43de-a094-9cbc71da8fc6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='DataTables_Table_0']/tbody/tr/td[7]/button</value>
      <webElementGuid>14da2032-6646-4d7c-a263-3ba1784c3d63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Persetujuan Teknis Pengelolaan Limbah Bahan Berbahaya dan Beracun'])[1]/preceding::button[1]</value>
      <webElementGuid>cc11f969-623f-49dd-b71d-2f1945226db7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Persetujuan Teknis Pengelolaan Limbah Bahan Berbahaya dan Beracun'])[2]/preceding::button[1]</value>
      <webElementGuid>18606fe9-7dee-41f1-9b2c-5a51184ec34e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Disable']/parent::*</value>
      <webElementGuid>2e1e56dd-aabf-4514-b39a-b90239fb173c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[7]/button</value>
      <webElementGuid>b0fa9c4f-83c6-41b0-aefa-fbd47f1d1020</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = '
                             Disable
                        ' or . = '
                             Disable
                        ')]</value>
      <webElementGuid>7919822f-e4bc-4e9f-9041-3d2e58918614</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
