<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Perizinan-Aktif</name>
   <tag></tag>
   <elementGuidId>be1c2642-7546-4e25-9422-1498d3d35c35</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.apexcharts-menu-icon</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='apexchartsfh78kppz']/div[3]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#apexchartsfh78kppz >> internal:attr=[title=&quot;Menu&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>42d5589f-6491-4b4f-aa81-3924d73c37f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>apexcharts-menu-icon</value>
      <webElementGuid>868fc667-4ce9-40b9-913b-2ff86788723d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Menu</value>
      <webElementGuid>e7dd6cb4-5187-40ef-9f36-5058bb8aaba8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;apexchartsfh78kppz&quot;)/div[@class=&quot;apexcharts-toolbar&quot;]/div[@class=&quot;apexcharts-menu-icon&quot;]</value>
      <webElementGuid>f15834b9-d49b-436e-9f9b-183c347dd821</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='apexchartsfh78kppz']/div[3]/div</value>
      <webElementGuid>ab13ea35-8c39-4f0f-821b-3f706a30aa78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Perdagangan dan Usaha Umum'])[1]/following::div[11]</value>
      <webElementGuid>7313a0d7-988c-414c-82d3-ce033cafa64c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Perizinan Aktif'])[1]/following::div[14]</value>
      <webElementGuid>0991d3a2-15d6-4501-99a3-9ff060a3d3c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Download SVG'])[1]/preceding::div[1]</value>
      <webElementGuid>8d4a0192-0b9c-47d4-9851-9b27306f966a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Download PNG'])[1]/preceding::div[2]</value>
      <webElementGuid>1dd8373b-44c0-4d41-97e9-6ddcfcb39634</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div[3]/div</value>
      <webElementGuid>6f0976b1-7b3b-44a2-9081-ffe70b9b1d4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@title = 'Menu']</value>
      <webElementGuid>1fdfb9b6-1065-4d71-9e8a-57f6b0dd66b8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
