<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Perizinan-sedang-dproses</name>
   <tag></tag>
   <elementGuidId>72683e4a-cda4-4c29-b72c-d4f5694540f3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#apexchartsxkmvsjhb > div.apexcharts-toolbar > div.apexcharts-menu-icon</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='apexchartsxkmvsjhb']/div[2]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#apexchartsxkmvsjhb >> internal:attr=[title=&quot;Menu&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>5ca17711-d176-4d60-8c8d-d87cd5f3ff79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>apexcharts-menu-icon</value>
      <webElementGuid>2c34421f-c3ea-4ec5-9eed-9ac956013bb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Menu</value>
      <webElementGuid>cc9509ab-7038-4eba-8a45-e0cac49536aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;apexchartsxkmvsjhb&quot;)/div[@class=&quot;apexcharts-toolbar&quot;]/div[@class=&quot;apexcharts-menu-icon&quot;]</value>
      <webElementGuid>59700212-b339-4c9e-83ce-6e5e94c84d54</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='apexchartsxkmvsjhb']/div[2]/div</value>
      <webElementGuid>633b0770-f024-4fb0-b8a9-89a8c67fa149</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Request:'])[3]/following::div[4]</value>
      <webElementGuid>4525a0ba-996a-4867-aa8f-b48fbf89f359</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Request:'])[2]/following::div[9]</value>
      <webElementGuid>f15cb1ce-a5c3-450d-a708-4ed79b96d3d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Download SVG'])[2]/preceding::div[1]</value>
      <webElementGuid>c8341960-03a9-49e1-bf00-9c27250000cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Download PNG'])[2]/preceding::div[2]</value>
      <webElementGuid>d82d7514-2b5c-48db-b87a-365f07a2a988</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/div/div[2]/div</value>
      <webElementGuid>2178700e-b9de-4621-8310-a48bef8a9887</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@title = 'Menu']</value>
      <webElementGuid>07c09ffe-758f-4ab1-813d-8fc97df3c0a2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
