<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Proses-Perizinan-Perizinan-Berakhir</name>
   <tag></tag>
   <elementGuidId>2c4d2400-c4c2-46e9-8b20-a7ede659f599</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#counter-habis</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//h4[@id='counter-habis']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#counter-habis</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h4</value>
      <webElementGuid>bd9a3422-ad2b-470d-a262-ea468b0d384a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fw-bold text-danger</value>
      <webElementGuid>70f6599e-2dd1-47a1-a1b8-0faa3df5d7c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>counter-habis</value>
      <webElementGuid>5f62b338-f244-4c2d-9ade-5c86904182e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>1c23b8f7-065e-41e8-b709-97857b10aded</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;counter-habis&quot;)</value>
      <webElementGuid>865886d6-0589-4a29-9aea-e040c0fb351d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//h4[@id='counter-habis']</value>
      <webElementGuid>20bb1b1b-affb-4ed8-bfa1-8c392cc4f534</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='layout-wrapper']/div[2]/div/div/div[2]/div/div[2]/div[3]/div/div/h4</value>
      <webElementGuid>e0c70eff-24e8-47bf-885a-10c49a719b6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-- Semua Perusahaan --'])[2]/following::h4[3]</value>
      <webElementGuid>b0f2c742-a860-4b54-9e17-5b29752dc2e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Proses Perizinan'])[1]/following::h4[3]</value>
      <webElementGuid>fc82f6ba-692d-46e9-8a14-802359ff79b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Perizinan Aktif'])[1]/preceding::h4[1]</value>
      <webElementGuid>83cf2e49-93c1-4d82-83e3-7b555721c2d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Perdagangan dan Usaha Umum'])[1]/preceding::h4[2]</value>
      <webElementGuid>06534b15-2817-482f-a6b3-e31deacfeb60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/h4</value>
      <webElementGuid>3961c1f6-398d-447f-b38a-07232c581ee7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h4[@id = 'counter-habis' and (text() = '0' or . = '0')]</value>
      <webElementGuid>6d6d0a70-dbae-4f1b-acd9-170b56aa5ad6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
