<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Proses-Perizinan-Perizinan-Terbit</name>
   <tag></tag>
   <elementGuidId>41a38d32-37dd-4941-8051-1cb10524fe59</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#counter-terbit</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//h4[@id='counter-terbit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;0 Perizinan Terbit&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h4</value>
      <webElementGuid>ff52e814-72aa-4cdb-ad93-52b6aa0d4fcc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fw-bold text-success</value>
      <webElementGuid>d50a49cb-6e7e-45e8-8e1b-ab8957647017</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>counter-terbit</value>
      <webElementGuid>c6ef4e57-abf4-46ca-a109-3e3dd7f34a26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>16fa03fc-896e-44b5-8fd5-68502f38440e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;counter-terbit&quot;)</value>
      <webElementGuid>96e516e2-5abd-49a5-9433-039b607ae7ad</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//h4[@id='counter-terbit']</value>
      <webElementGuid>5ffd727b-1a6d-4120-ab23-a84c3e1e6952</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='layout-wrapper']/div[2]/div/div/div[2]/div/div[2]/div/a/div/div/h4</value>
      <webElementGuid>864898c2-b5fc-4609-8656-3e9fa8eab06e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-- Semua Perusahaan --'])[2]/following::h4[1]</value>
      <webElementGuid>21090dc4-6f25-46ab-92a1-68e67840265d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Proses Perizinan'])[1]/following::h4[1]</value>
      <webElementGuid>32c560a5-15ed-44b3-9d04-52389bfc706f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Perizinan Aktif'])[1]/preceding::h4[3]</value>
      <webElementGuid>86f71af9-46f0-4a9c-84f6-400f34531c4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Perdagangan dan Usaha Umum'])[1]/preceding::h4[4]</value>
      <webElementGuid>8f032e63-baef-4532-852e-7adf5184e449</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/div/div/h4</value>
      <webElementGuid>f36e2168-7ceb-4614-8a7d-cfe636a3843d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h4[@id = 'counter-terbit' and (text() = '0' or . = '0')]</value>
      <webElementGuid>4cdb72a9-1b31-4a26-a4a1-edcac8007661</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
