<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nama Instansi Penerbit (ENG)</name>
   <tag></tag>
   <elementGuidId>fdcaa184-d58b-425f-a416-cd8d9fca6efc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#authoritynameeng</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='authoritynameeng']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Nama Instansi Penerbit (ENG)&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d294e814-5e77-4ae0-8921-a5d7211bd51b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c7d4652a-1d4f-46fe-8cfa-4e66a44752c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control </value>
      <webElementGuid>f88139d4-68f5-4cfa-bb7d-6a2118027f3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>authoritynameeng</value>
      <webElementGuid>252815c8-f05b-4633-8f2c-fc76a9a3cc1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>authoritynameeng</value>
      <webElementGuid>83ed33eb-c5ee-4ba7-afca-2cee0b21a84b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan Nama Instansi Penerbit</value>
      <webElementGuid>1452a96c-e8f8-432b-8697-ec1de9e7768f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;authoritynameeng&quot;)</value>
      <webElementGuid>fcf15c59-151c-421b-a9ca-c5e022ea493c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='authoritynameeng']</value>
      <webElementGuid>56a46a5d-4a01-4905-aced-8909c2fb43ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='layout-wrapper']/div[2]/div/div/div[2]/div/div/div/div/div/form/div[2]/input</value>
      <webElementGuid>7c232d26-4342-4dea-837d-076462fe4cdd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>ee945e24-a012-4f84-8c7c-c557d49525f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'authoritynameeng' and @name = 'authoritynameeng' and @placeholder = 'Masukkan Nama Instansi Penerbit']</value>
      <webElementGuid>f0dd64c4-5bf1-4a66-913c-3a8b37e35a57</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
