<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_nama-dok-pendukung</name>
   <tag></tag>
   <elementGuidId>2a6d608f-5309-4ce8-bc0b-b565c59b5026</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='nama_dokumen[]']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;nama_dokumen[]&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Nama dokumen&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>440f4ac8-1b4d-4f50-af05-c24644feca57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2f307e29-0c2f-4825-b3a0-0d4b03be5964</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>nama_dokumen[]</value>
      <webElementGuid>ade8e0cf-1e70-43d8-8f93-2882b92357fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control me-2</value>
      <webElementGuid>ff4d53a9-17d7-4d03-ac7c-6a734f877859</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Nama dokumen</value>
      <webElementGuid>ac84fda3-2cda-418b-8f76-8eb6eebcc3f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dokumen-container&quot;)/div[@class=&quot;dokumen-item d-flex align-items-center mb-2&quot;]/input[@class=&quot;form-control me-2&quot;]</value>
      <webElementGuid>96e9a483-a9d3-4b0c-b849-9e920b85e1ff</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='nama_dokumen[]']</value>
      <webElementGuid>bbb2ccfe-0433-4d6b-aaf9-e3b43d92f16f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dokumen-container']/div/input</value>
      <webElementGuid>84f21581-3e89-4e0f-9c75-e3096fa2d26a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/input</value>
      <webElementGuid>86a5405f-4293-4d22-9af0-6b0fb4062526</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'nama_dokumen[]' and @placeholder = 'Nama dokumen']</value>
      <webElementGuid>bdab4350-18d2-400b-b614-80e463aa5ef2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
