<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__targetWaktu</name>
   <tag></tag>
   <elementGuidId>482a0fc2-80bc-4980-b583-a3a1eb2a440c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#targetWaktu</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='targetWaktu']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#targetWaktu</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c92a7e1b-5184-4f94-a8a3-a9b1e1353ed0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>date</value>
      <webElementGuid>da93e3b5-4a30-40f6-af81-4daaac23dda9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>4e2fed74-49a1-4965-bdc3-6003f910d75b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>permittargettime</value>
      <webElementGuid>0b4c032b-418d-4c8d-8b59-949fa1a9e2df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>targetWaktu</value>
      <webElementGuid>7132c921-610d-44e3-b1fb-21cbf606eb8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;targetWaktu&quot;)</value>
      <webElementGuid>40c8bc13-8bd8-440a-9d25-a0df8539ec4d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='targetWaktu']</value>
      <webElementGuid>336c3ba0-ffa0-466d-9e6e-a5c45a827040</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form-permohonan-perubahan']/div/div[3]/input</value>
      <webElementGuid>7b7e4517-82cb-4c6a-9492-785441660ce4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>c335702e-b5ae-4d2a-a1b8-2009d0d1cffe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'date' and @name = 'permittargettime' and @id = 'targetWaktu']</value>
      <webElementGuid>4b33fa08-e8a3-48ee-b7de-22867554d5dd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
