<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Detail</name>
   <tag></tag>
   <elementGuidId>35e8448d-fd46-4c11-b028-a90d3bb97053</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='DataTables_Table_0']/tbody/tr/td[5]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.btn.btn-info.btn-sm.m-1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot; Detail&quot;i] >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>eb9be4a3-709f-406d-9e19-ee176e4b0166</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://ocp-mmsgi.alfahuma.biz.id/master/authority/eyJpdiI6ImtydDhCZGp2RjhQSUZ3bVdTSGFtUWc9PSIsInZhbHVlIjoiUms0YnNSbzlsNzNFY08vT3BXSklhcnhBZ1IxbmNCajJJaDVjL0U3ZS9CWU4rYlVmYjRRaENLa0c5MHhqRjFSNiIsIm1hYyI6IjdiOGVmOWI1Y2VhZDdkZjllMmY3MGQ2N2FhNzA3NGFjOWNjYmEwODhlOWY2ZThmMDIxOGMxNGRiNmU3Yzg0NjUiLCJ0YWciOiIifQ==</value>
      <webElementGuid>2591a385-179d-42ce-a7ff-5d41ac7dd746</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-info btn-sm m-1</value>
      <webElementGuid>1b9bc339-c4ef-4d99-a3fd-44ef93ac9d55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                         Detail
                    </value>
      <webElementGuid>ca5512aa-d518-4d49-a8ed-41da0dea978c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DataTables_Table_0&quot;)/tbody[1]/tr[@class=&quot;odd&quot;]/td[@class=&quot;text-center&quot;]/a[@class=&quot;btn btn-info btn-sm m-1&quot;]</value>
      <webElementGuid>a2622175-1f2c-4627-8f8d-f490601238c0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='DataTables_Table_0']/tbody/tr/td[5]/a</value>
      <webElementGuid>78b6e550-c14e-4616-9109-9d56db29d64f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ENABLE'])[2]/following::a[1]</value>
      <webElementGuid>c6dc5799-18f1-4fc4-962b-cbf19603cec5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Menteri Pekerjaan Umum dan Perumahan Rakyat'])[2]/following::a[1]</value>
      <webElementGuid>552d58b1-a621-46bb-bf46-94b1b74071e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Detail']/parent::*</value>
      <webElementGuid>bdf4fbda-d47c-491a-a909-aa5e7cc20730</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://ocp-mmsgi.alfahuma.biz.id/master/authority/eyJpdiI6ImtydDhCZGp2RjhQSUZ3bVdTSGFtUWc9PSIsInZhbHVlIjoiUms0YnNSbzlsNzNFY08vT3BXSklhcnhBZ1IxbmNCajJJaDVjL0U3ZS9CWU4rYlVmYjRRaENLa0c5MHhqRjFSNiIsIm1hYyI6IjdiOGVmOWI1Y2VhZDdkZjllMmY3MGQ2N2FhNzA3NGFjOWNjYmEwODhlOWY2ZThmMDIxOGMxNGRiNmU3Yzg0NjUiLCJ0YWciOiIifQ==')]</value>
      <webElementGuid>7d73b471-371f-4dbf-8036-17828d7d3e43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[5]/a</value>
      <webElementGuid>38ffcfa3-9e49-485d-9ef6-e8debb7ed8f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://ocp-mmsgi.alfahuma.biz.id/master/authority/eyJpdiI6ImtydDhCZGp2RjhQSUZ3bVdTSGFtUWc9PSIsInZhbHVlIjoiUms0YnNSbzlsNzNFY08vT3BXSklhcnhBZ1IxbmNCajJJaDVjL0U3ZS9CWU4rYlVmYjRRaENLa0c5MHhqRjFSNiIsIm1hYyI6IjdiOGVmOWI1Y2VhZDdkZjllMmY3MGQ2N2FhNzA3NGFjOWNjYmEwODhlOWY2ZThmMDIxOGMxNGRiNmU3Yzg0NjUiLCJ0YWciOiIifQ==' and (text() = '
                         Detail
                    ' or . = '
                         Detail
                    ')]</value>
      <webElementGuid>0796ee89-57d9-402e-9147-82025ea905a2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
