<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Detail</name>
   <tag></tag>
   <elementGuidId>00e1d431-703d-4097-ad44-859a50c584ff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='DataTables_Table_0']/tbody/tr/td[7]/a/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.bx.bx-show.font-size-16.align-middle.me-1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=row[name=&quot;1 Testing Type Permit Untuk Keperluan Testing Type Permit Pertambangan Pertambangan Batu Bara ENABLE  Detail  Edit  Disable&quot;i] >> internal:role=link >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>dc03ea23-7111-4934-b4c6-2507c1da0efd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bx bx-show font-size-16 align-middle me-1</value>
      <webElementGuid>83488211-86a5-418b-819f-88df130142cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DataTables_Table_0&quot;)/tbody[1]/tr[@class=&quot;odd&quot;]/td[@class=&quot;text-center&quot;]/a[@class=&quot;btn btn-info btn-sm m-1&quot;]/i[@class=&quot;bx bx-show font-size-16 align-middle me-1&quot;]</value>
      <webElementGuid>09e9e864-bb5b-4e23-95ed-ef5cf18a897e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='DataTables_Table_0']/tbody/tr/td[7]/a/i</value>
      <webElementGuid>db93fef1-2acc-44f3-bd82-4b071cb0db55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[7]/a/i</value>
      <webElementGuid>de99ac09-8fdd-488e-91d9-edb6d76c3bd9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
