<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nama Tipe Perizinan (ENG)_typepermitnameeng</name>
   <tag></tag>
   <elementGuidId>c3ebe4af-a47f-44fc-a5d1-b0f3fa84a56a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='typepermitnameeng']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#typepermitnameeng</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Nama Tipe Perizinan (ENG)&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5c228260-3775-44ea-a632-2c9467dd295e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9517df34-57ff-4537-af08-eb4d3114f849</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control </value>
      <webElementGuid>46610d71-41ce-46a7-bf88-68106803fa9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>typepermitnameeng</value>
      <webElementGuid>cd2b7c2a-6d96-4e3d-b3ef-4e00b64d6e27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>typepermitnameeng</value>
      <webElementGuid>a11ed3b0-cba5-44a3-a4ba-8a4a19789182</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan nama tipe perizinan</value>
      <webElementGuid>c5e5f57c-9d87-4547-8794-0107df4f84cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;typepermitnameeng&quot;)</value>
      <webElementGuid>c2261706-79d2-45f4-ab25-19147a976427</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='typepermitnameeng']</value>
      <webElementGuid>eb28e7df-540d-498e-b68c-98b1d37cc31a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='layout-wrapper']/div[2]/div/div/div[2]/div/div/div/div/div/form/div[2]/input</value>
      <webElementGuid>5e454bcf-4fd8-4c0b-a435-ec509e5bc9be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>7f50aa4d-d5ff-4c43-a6f3-bbe1ce3ba350</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'typepermitnameeng' and @name = 'typepermitnameeng' and @placeholder = 'Masukkan nama tipe perizinan']</value>
      <webElementGuid>63d1cbd5-ea34-4f55-b7b8-c88d5c972d05</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
