<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Perpanjangan</name>
   <tag></tag>
   <elementGuidId>bfab1336-7851-4993-83f6-d2feebce313c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.dropdown-item.active</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='topnav-menu-content']/ul/li[2]/div/div/div/a[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Perpanjangan&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>854b1aea-917d-412f-8975-31866a3582da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://staging-ocp-lms.mmsgroup.co.id/perizinan/permohonan/perpanjang</value>
      <webElementGuid>fad462ab-a4e0-46e5-a7b5-c5af9527aff7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-item active</value>
      <webElementGuid>3c9d9577-705d-4e0c-a977-5e640f1a07f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>key</name>
      <type>Main</type>
      <value>t-69</value>
      <webElementGuid>d7bbb4cc-a553-4d5e-bd42-61d01e4190ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                                                        Perpanjangan
                                                                    </value>
      <webElementGuid>6f5ac81a-0a8c-47bc-b196-aa413debeca6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;topnav-menu-content&quot;)/ul[@class=&quot;navbar-nav active&quot;]/li[@class=&quot;nav-item dropdown active&quot;]/div[@class=&quot;dropdown-menu active&quot;]/div[@class=&quot;dropdown active&quot;]/div[@class=&quot;dropdown-menu active&quot;]/a[@class=&quot;dropdown-item active&quot;]</value>
      <webElementGuid>dec80a17-698d-4179-a56a-6fc0d17b721d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='topnav-menu-content']/ul/li[2]/div/div/div/a[2]</value>
      <webElementGuid>f6662515-578c-4c29-bb9d-0b6b62800ae1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Perpanjangan')]</value>
      <webElementGuid>326c1f56-36b1-477c-bd33-79bfdf09335a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Baru'])[1]/following::a[1]</value>
      <webElementGuid>7c6d62c6-5f73-469a-837b-4a732e0e9505</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Permohonan'])[1]/following::a[2]</value>
      <webElementGuid>cd182b48-2558-4fa7-b4e5-8c35a6d9c54f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Perubahan'])[1]/preceding::a[1]</value>
      <webElementGuid>291e1dd3-1c8f-4b57-b4ce-525d6903b970</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Daftar Request Perizinan'])[1]/preceding::a[2]</value>
      <webElementGuid>63c54b56-9ce9-402c-b8fc-dddc5310e7eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Perpanjangan']/parent::*</value>
      <webElementGuid>8c54e3a8-bb57-4bae-9897-9592615abd49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://staging-ocp-lms.mmsgroup.co.id/perizinan/permohonan/perpanjang')]</value>
      <webElementGuid>9914d314-6c84-4af1-ad71-b374f1f9dd62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/div/div/div/a[2]</value>
      <webElementGuid>d75a92f4-85f2-40ae-975b-c9b3dd719aee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://staging-ocp-lms.mmsgroup.co.id/perizinan/permohonan/perpanjang' and (text() = '
                                                                        Perpanjangan
                                                                    ' or . = '
                                                                        Perpanjangan
                                                                    ')]</value>
      <webElementGuid>d3c66a64-1378-474b-829f-a70ec708437d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
