<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_targetWaktu</name>
   <tag></tag>
   <elementGuidId>0ead9828-9b25-4ace-82b9-3df05c7257de</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#targetWaktu</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='targetWaktu']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#targetWaktu</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>31944c5e-dbbc-4212-8956-8e6b64f14c6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>date</value>
      <webElementGuid>29e5f0bb-4d0f-42ee-ac38-385efd07e536</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>dc6cb9a9-9a4c-4f8b-97e9-8719605dd156</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>permittargettime</value>
      <webElementGuid>ea05fc7a-4565-4e20-9d3e-eb26e1f8c295</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>targetWaktu</value>
      <webElementGuid>95914801-2178-462e-888e-657e7ef451fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;targetWaktu&quot;)</value>
      <webElementGuid>524f6817-0f01-430b-8830-2ce1be0f9bcb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='targetWaktu']</value>
      <webElementGuid>7c9cdef5-18bd-4dd1-a4d1-348c33eb949e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form-permohonan-perpanjangan']/div/div[3]/input</value>
      <webElementGuid>ec4aa58e-7ec9-423c-9f3e-fd76d0c3d249</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>22e9f1a9-66d5-4b58-bf80-2ccbe035d395</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'date' and @name = 'permittargettime' and @id = 'targetWaktu']</value>
      <webElementGuid>197b048e-f242-46ea-beee-079dac642c0b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
