<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Informasi-perizinan-aktif-jenis-download</name>
   <tag></tag>
   <elementGuidId>6c4cf29f-320a-4aac-99d5-cdaea3653a76</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='apexchartss7mow0is']/div[3]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.apexcharts-menu-icon</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#apexchartss7mow0is >> internal:attr=[title=&quot;Menu&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>ab8d7c0c-0e6b-45c9-b1a9-06b3809be0db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>apexcharts-menu-icon</value>
      <webElementGuid>86daeddb-297f-41a6-bada-61e2c208a2cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Menu</value>
      <webElementGuid>909550f1-3343-4f63-95d2-d4965603a95b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;apexchartss7mow0is&quot;)/div[@class=&quot;apexcharts-toolbar&quot;]/div[@class=&quot;apexcharts-menu-icon&quot;]</value>
      <webElementGuid>21787d0f-b127-410d-961a-c0bea9f60a6c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='apexchartss7mow0is']/div[3]/div</value>
      <webElementGuid>43e829d4-cd5c-46bf-8b29-12109a5d1c5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Perizinan Usaha'])[1]/following::div[11]</value>
      <webElementGuid>91158fd3-416a-43cf-8ae2-2b55239e5bad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Perizinan Lingkungan'])[1]/following::div[11]</value>
      <webElementGuid>f7d51e4e-56d0-4d5b-a16b-f87025efe84a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Download SVG'])[1]/preceding::div[1]</value>
      <webElementGuid>d5a212fc-6a06-49b4-a17f-a6fe4d9645f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Download PNG'])[1]/preceding::div[2]</value>
      <webElementGuid>4992f7e0-6733-4605-a4a2-feebf1d4c9c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[3]/div/div/div[3]/div</value>
      <webElementGuid>2dd32ad6-2df7-43ae-8d0f-81f1c7293fac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@title = 'Menu']</value>
      <webElementGuid>0fb0b26a-9149-41ff-bfa0-2db850f450f0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
