<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Kembali</name>
   <tag></tag>
   <elementGuidId>1c6c5b3c-cf99-4e1e-b59c-6298f92d6e4e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@type='button']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.btn.btn-secondary.w-100.mb-3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot; Kembali&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>0bce8569-6304-43af-9808-16d62ad1f0df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://ocp-mmsgi.alfahuma.biz.id/daftar-request-perizinan/detail/0199c0e4-ffee-71cf-afba-ea1748fb2f9c</value>
      <webElementGuid>afba161e-9960-480d-924d-98083b7e56aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>78b04b7c-3a9e-4865-a680-fe4c1d58e297</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-secondary w-100 mb-3</value>
      <webElementGuid>4156da79-bd45-4275-ac4e-ce22c8e42d2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
							 Kembali
						</value>
      <webElementGuid>7d9102e8-8274-4f38-a579-8769d9fb0d96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;layout-wrapper&quot;)/div[@class=&quot;main-content&quot;]/div[@class=&quot;page-content&quot;]/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;card&quot;]/div[@class=&quot;card-body&quot;]/div[@class=&quot;border-custom p-3 mb-4&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-4&quot;]/a[@class=&quot;btn btn-secondary w-100 mb-3&quot;]</value>
      <webElementGuid>4982b292-6d4c-465f-8b80-0c177cf83552</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@type='button']</value>
      <webElementGuid>03efcb13-bc64-4248-97e1-bd9d8fd1047f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='layout-wrapper']/div[2]/div/div/div[2]/div/div/div/div[2]/a</value>
      <webElementGuid>0bac5ba7-83d0-426f-b991-4283e702962a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=': Disetujui'])[1]/following::a[1]</value>
      <webElementGuid>4bd1a97b-d17e-4076-82f0-d63214842c79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Status Sub Permit'])[1]/following::a[1]</value>
      <webElementGuid>3742bffe-6a70-4346-838d-578804fb0dca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ajukan Review ke Div Head'])[1]/preceding::a[1]</value>
      <webElementGuid>8884596a-0d0a-4ace-a39b-d566c28f1c21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Note Teknis : Dokumen Salah Upload'])[1]/preceding::a[1]</value>
      <webElementGuid>92586f16-d4a1-441c-8639-e003c931beb6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Kembali']/parent::*</value>
      <webElementGuid>2dd53d52-c962-4901-b5a5-38129d153745</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://ocp-mmsgi.alfahuma.biz.id/daftar-request-perizinan/detail/0199c0e4-ffee-71cf-afba-ea1748fb2f9c')]</value>
      <webElementGuid>8b881a9b-4ea6-48a8-98dc-5ab2b92ad8d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div[2]/a</value>
      <webElementGuid>e76d2d22-6697-47e7-a0d5-27fd6d22c94c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://ocp-mmsgi.alfahuma.biz.id/daftar-request-perizinan/detail/0199c0e4-ffee-71cf-afba-ea1748fb2f9c' and @type = 'button' and (text() = '
							 Kembali
						' or . = '
							 Kembali
						')]</value>
      <webElementGuid>ff5451f2-de46-4dee-a7d2-b83f180f65cc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
