<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Perpanjangan</name>
   <tag></tag>
   <elementGuidId>8262ba2e-79eb-431c-8b11-ba29b9a4ea37</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='topnav-menu-content']/ul/li[2]/div/div/div/a[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Perpanjangan&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>4a07f288-ebf2-4f82-a4a9-290d7b8f39d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://staging-ocp-lms.mmsgroup.co.id/perizinan/permohonan/perpanjang</value>
      <webElementGuid>6ba855a2-d4bf-454e-acaf-746301f9381b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-item</value>
      <webElementGuid>bd975bf1-030b-45f5-86e7-b5a09e32e693</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>key</name>
      <type>Main</type>
      <value>t-69</value>
      <webElementGuid>cc565668-a706-4b4f-a918-d6435de0c142</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                                                        Perpanjangan
                                                                    </value>
      <webElementGuid>4a936877-9418-490f-b863-c54da15b9d07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;topnav-menu-content&quot;)/ul[@class=&quot;navbar-nav active&quot;]/li[@class=&quot;nav-item dropdown active&quot;]/div[@class=&quot;dropdown-menu active&quot;]/div[@class=&quot;dropdown active&quot;]/div[@class=&quot;dropdown-menu active&quot;]/a[@class=&quot;dropdown-item&quot;]</value>
      <webElementGuid>a015eef4-8909-4ef6-bb67-4fbfd14fdf45</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='topnav-menu-content']/ul/li[2]/div/div/div/a[2]</value>
      <webElementGuid>579b6ec4-73f6-4eb7-a5b4-1a332815ea14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Perpanjangan')]</value>
      <webElementGuid>57329790-7f7f-4153-8a8b-9efed3ed35c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Baru'])[1]/following::a[1]</value>
      <webElementGuid>599cc541-0fbc-4401-8161-ed3316cba8e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Permohonan'])[1]/following::a[2]</value>
      <webElementGuid>8dc35c30-3cab-4e23-a998-4225cd114b1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Perubahan'])[1]/preceding::a[1]</value>
      <webElementGuid>e17578e5-d349-493f-9fd9-836da38207f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Daftar Request Perizinan'])[1]/preceding::a[2]</value>
      <webElementGuid>f9005f53-f0b1-4793-9c76-9adda672f92b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Perpanjangan']/parent::*</value>
      <webElementGuid>e9d73964-6a07-4427-a612-f71e73991206</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://staging-ocp-lms.mmsgroup.co.id/perizinan/permohonan/perpanjang')]</value>
      <webElementGuid>9ba1e445-a526-4e7b-9672-7e09c33cacc5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/div/div/div/a[2]</value>
      <webElementGuid>c5314e6e-65bf-4bce-b6b9-2eb92f17efd2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://staging-ocp-lms.mmsgroup.co.id/perizinan/permohonan/perpanjang' and (text() = '
                                                                        Perpanjangan
                                                                    ' or . = '
                                                                        Perpanjangan
                                                                    ')]</value>
      <webElementGuid>a638f7f4-d15a-4e62-a9b4-e64dda9a73f5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
