<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Dasar Hukum</name>
   <tag></tag>
   <elementGuidId>35841686-174c-44cf-b7e7-684afd56017b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='cardInformasi']/div[2]/div/div/div/span/button[2]/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.fa.fa-pencil-alt</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;&quot;i] >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>a36f2ed3-e3bd-468a-b6c6-42456013907b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-pencil-alt</value>
      <webElementGuid>3807c4dd-792a-472a-b335-de7a00902eec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cardInformasi&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-6 mb-3&quot;]/div[@class=&quot;border-custom p-2&quot;]/div[@class=&quot;d-flex justify-content-between align-items-center&quot;]/span[1]/button[@class=&quot;btn btn-warning btn-sm&quot;]/i[@class=&quot;fa fa-pencil-alt&quot;]</value>
      <webElementGuid>bcec9335-2190-4412-891d-dfe551629863</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cardInformasi']/div[2]/div/div/div/span/button[2]/i</value>
      <webElementGuid>ef146ecc-2284-4d4f-80de-ae8e4690765c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]/i</value>
      <webElementGuid>b4e9bd57-09d9-4b44-a40a-5de13b7249d7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
