<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span__select-perizinan-yg-diajukan</name>
   <tag></tag>
   <elementGuidId>fb6aaaef-617c-41d5-8a50-c4dce5a5ae16</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#select2-categorypermitid-dz-container</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-categorypermitid-dz-container']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#select2-categorypermitid-dz-container</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>32913829-0e3b-423c-8264-36a000d1d173</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>ebb465b4-60ba-4404-b0e6-48aa373e6d0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-categorypermitid-dz-container</value>
      <webElementGuid>42318082-5955-4d9b-88e6-5ef0c32c8875</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>0ab93868-446c-4b81-8972-b831d0769786</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>b11a1ce1-35c6-419f-b701-859280d84faa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>-- Pilih --</value>
      <webElementGuid>6ca8c4e9-3558-4b13-82ee-603bf4cf52ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>-- Pilih --</value>
      <webElementGuid>f02a937a-5a2d-4183-82c1-0f400bf34c48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-categorypermitid-dz-container&quot;)</value>
      <webElementGuid>c7fc4965-7137-49f9-aa83-aed7130fd0b4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-categorypermitid-dz-container']</value>
      <webElementGuid>fefb14d1-0466-43fd-95ec-7e492caf6c49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form-permohonan-baru']/div/div[2]/span/span/span/span</value>
      <webElementGuid>0c7d5c3e-4903-4f84-a4ee-4c81f20aa2a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[1]/following::span[4]</value>
      <webElementGuid>61977d4c-67cc-40bc-a0b3-8bc081617651</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[2]/preceding::span[3]</value>
      <webElementGuid>98a02bde-f8b4-4769-902b-56d8076e3989</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/span/span/span/span</value>
      <webElementGuid>73b5c1a5-e281-4184-b71e-22f2520a218e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-categorypermitid-dz-container' and @title = '-- Pilih --' and (text() = '-- Pilih --' or . = '-- Pilih --')]</value>
      <webElementGuid>dcfbfb48-617f-44fa-b71d-4f46117fbd68</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
