<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Tipe Izin-utama</name>
   <tag></tag>
   <elementGuidId>21fc2190-9775-4090-acbf-e407c75c3af5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#radio-utama</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='radio-utama']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Perizinan Utama&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>891ab5cd-c427-4361-afea-a518639621d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input</value>
      <webElementGuid>718c47db-47a9-47f4-b106-9211be03633f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>abb585d5-025f-406a-ab4c-66d15ba6233d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>subpermittype</value>
      <webElementGuid>d4944c4b-2de4-4d28-ac1f-13d0fb0bbdcc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>radio-utama</value>
      <webElementGuid>1a75473e-16ff-4c83-a741-8c846c57beb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>utama</value>
      <webElementGuid>8ac80047-bbc6-4423-a1f7-c33c0822a607</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;radio-utama&quot;)</value>
      <webElementGuid>a277b86d-99a9-45bd-bba6-4f394cb8568a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='radio-utama']</value>
      <webElementGuid>b917ab02-63c0-4343-a0ed-09ace7a4bd84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modalContent']/div/div[2]/div/input</value>
      <webElementGuid>7d5bfa7c-eba6-4991-8883-52bef16279b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>5a71ab2e-4a26-400e-a31e-d1aa968bcd60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'subpermittype' and @id = 'radio-utama']</value>
      <webElementGuid>699772fe-aa62-4aba-8ef4-cf1fd393571c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
