<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Lengkapi-Izin-Utama</name>
   <tag></tag>
   <elementGuidId>0ce33f68-47e6-4960-916d-d6be7a5fe2c1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@type='button']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.btn.btn-primary.btn-sm.btnProses</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Lengkapi&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>38d612f5-dbf8-467e-b1c2-ee4470ddd313</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://ocp-mmsgi.alfahuma.biz.id/daftar-request-perizinan/detail-sub-permit/0199c0e5-c2e6-71e6-adec-8d32e35c5478</value>
      <webElementGuid>1783d3a8-0e82-4ba9-8eb6-1dd293b3fcf1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>6e373e84-6ae3-49e7-b530-e42a89955386</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary btn-sm btnProses</value>
      <webElementGuid>7a1bc09b-e432-41a7-8200-5b41f3eef0c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Lengkapi</value>
      <webElementGuid>763203bd-40bb-4c98-9026-c77ede0e59dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;layout-wrapper&quot;)/div[@class=&quot;main-content&quot;]/div[@class=&quot;page-content&quot;]/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;card&quot;]/div[@class=&quot;card-body&quot;]/div[@class=&quot;formDaftar&quot;]/table[@class=&quot;table table-bordered table-sm table-striped dt-responsive nowrap w-100 yajra-datatable mb-4&quot;]/tbody[1]/tr[1]/td[@class=&quot;text-center&quot;]/div[@class=&quot;btn-group btn-group-sm&quot;]/a[@class=&quot;btn btn-primary btn-sm btnProses&quot;]</value>
      <webElementGuid>2c1e5dda-2b95-40ce-b122-77daf2ca2949</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@type='button']</value>
      <webElementGuid>8123e60a-01e3-43b0-be5e-53c55f0eb046</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='layout-wrapper']/div[2]/div/div/div[2]/div/div[2]/table/tbody/tr/td[8]/div/a</value>
      <webElementGuid>c9194387-4cae-48f3-9b8e-8036e7f26559</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Lengkapi')]</value>
      <webElementGuid>ee3f9a6c-b757-4ba8-8292-8329316d02ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Disetujui'])[1]/following::a[1]</value>
      <webElementGuid>329dd6c7-0609-403a-ad62-a249bffd9510</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pengelolaan Limbah'])[1]/following::a[1]</value>
      <webElementGuid>b4ad44f5-f1dc-40f7-a8b3-93d5147e7b73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sub Perizinan'])[1]/preceding::a[1]</value>
      <webElementGuid>855d01fb-02e6-4604-9777-46f3747852e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No'])[2]/preceding::a[1]</value>
      <webElementGuid>6a2242e9-1a71-4504-9247-bc2156d8f0eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Lengkapi']/parent::*</value>
      <webElementGuid>239ac571-8bc0-4b2c-b912-24e88e152092</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://ocp-mmsgi.alfahuma.biz.id/daftar-request-perizinan/detail-sub-permit/0199c0e5-c2e6-71e6-adec-8d32e35c5478')]</value>
      <webElementGuid>093aebfd-dd93-4768-a702-83fa407d9fd2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[8]/div/a</value>
      <webElementGuid>d20024eb-2450-43ae-bc6c-f38e587a2087</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://ocp-mmsgi.alfahuma.biz.id/daftar-request-perizinan/detail-sub-permit/0199c0e5-c2e6-71e6-adec-8d32e35c5478' and @type = 'button' and (text() = 'Lengkapi' or . = 'Lengkapi')]</value>
      <webElementGuid>2703658f-cafb-4214-81fd-02cadd9ba18b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
