<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Laporan</name>
   <tag></tag>
   <elementGuidId>e1725214-1baf-412d-9802-41e75b2251b7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#topnav-82 > span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='topnav-82']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Laporan&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>0c7abd7e-3262-47f7-9f36-2312c754784a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>key</name>
      <type>Main</type>
      <value>t-82</value>
      <webElementGuid>7dcf42ec-d214-463c-a027-6edcd40a4747</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Laporan</value>
      <webElementGuid>d2ce6121-ef15-4fd5-8bab-3aec9ea2a231</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;topnav-82&quot;)/span[1]</value>
      <webElementGuid>caa5f99f-bd1f-497f-bb50-7a9d83b82fc0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='topnav-82']/span</value>
      <webElementGuid>cf24bd1e-8f4e-4519-8efe-d110901b40c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='System Paramater'])[1]/following::span[1]</value>
      <webElementGuid>9db71447-8026-48f5-ad37-805c6fd40134</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Instansi Penerbit'])[1]/following::span[1]</value>
      <webElementGuid>0e9b3a7c-7b23-4283-964e-6507e0d1410e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Semua Laporan'])[1]/preceding::span[1]</value>
      <webElementGuid>95df7e41-9902-4320-9e21-f6957bc41a8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Download Laporan'])[1]/preceding::span[1]</value>
      <webElementGuid>ddb3c180-0838-483e-b01f-49527273a033</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Laporan']/parent::*</value>
      <webElementGuid>2853aed4-f284-41e6-adc8-8deb64237c69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[5]/a/span</value>
      <webElementGuid>700476ce-9f98-4ef3-a892-5be7a77e6fd6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Laporan' or . = 'Laporan')]</value>
      <webElementGuid>b6a0f118-d6ae-490c-acd4-3834b39a8631</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
