<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Simpan_Edit-Req-Perizinan</name>
   <tag></tag>
   <elementGuidId>c9329db1-5dc9-43ac-a396-5c360adbd8dc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#form-modal-modalKlarifikasiPerizinan > div.modal-footer.text-end > button.btn.btn-success.btn-sm > i.fa.fa-save</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='form-modal-modalKlarifikasiPerizinan']/div[2]/button/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot; Simpan&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>1ececf2b-3a7c-48fa-b017-92d22310e250</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-save</value>
      <webElementGuid>12eb5735-7bd9-4b1c-bc20-871a6936c977</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form-modal-modalKlarifikasiPerizinan&quot;)/div[@class=&quot;modal-footer text-end&quot;]/button[@class=&quot;btn btn-success btn-sm&quot;]/i[@class=&quot;fa fa-save&quot;]</value>
      <webElementGuid>ab8ae035-6f7f-4a44-af75-944c60b385ce</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form-modal-modalKlarifikasiPerizinan']/div[2]/button/i</value>
      <webElementGuid>72e54388-f9d4-42b6-a57d-a4f3f27a1910</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/form/div[2]/button/i</value>
      <webElementGuid>40c6c60a-da7d-4ff8-9a8c-1e2fe08ef99a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
