<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Next</name>
   <tag></tag>
   <elementGuidId>ebaaabe8-c67c-47d4-bbfd-373b0baeafbb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#DataTables_Table_0_next</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='DataTables_Table_0_next']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#DataTables_Table_0_next</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>1395b23b-0f1b-41b7-8bc6-784d5a40e7a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>paginate_button page-item next disabled</value>
      <webElementGuid>44eb7461-193d-44c2-b9ff-75b58d1b69dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>DataTables_Table_0_next</value>
      <webElementGuid>1b08bed0-bb0a-4a81-b360-b1c85a7b69d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Selanjutnya</value>
      <webElementGuid>1e4e805b-bcd8-4aa8-b005-3bf769b6267b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DataTables_Table_0_next&quot;)</value>
      <webElementGuid>7a3fa230-fb35-496a-aa3a-818b0fbabac7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='DataTables_Table_0_next']</value>
      <webElementGuid>3b39747f-42f6-4833-87c7-53c3d97a4c92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='DataTables_Table_0_paginate']/ul/li[3]</value>
      <webElementGuid>fb687afd-c6fc-43d4-85df-57521da95820</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sebelumnya'])[1]/following::li[2]</value>
      <webElementGuid>e3d23e27-ed1d-4536-8c49-125bea408ac7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Menampilkan data ke 1 sampai 6 dari 6 total data.'])[1]/following::li[3]</value>
      <webElementGuid>d5e284f8-acd9-4b4e-96cc-49acb85691db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Permintaan Dana'])[5]/preceding::li[1]</value>
      <webElementGuid>edc462cd-78ac-49ed-8f97-740012da631e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/ul/li[3]</value>
      <webElementGuid>fa6fc9f0-4bee-43ac-b0b6-6aca041a669b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'DataTables_Table_0_next' and (text() = 'Selanjutnya' or . = 'Selanjutnya')]</value>
      <webElementGuid>78ee1287-99a0-4b51-9e1b-85a3173b90d3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
