<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Perpanjangan</name>
   <tag></tag>
   <elementGuidId>f7a61d97-ab56-4bbf-9f1b-08fae92b6d18</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='topnav-menu-content']/ul/li[2]/div/div/div/a[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Perpanjangan&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>70ed9ace-b380-4935-8ad3-7682e8a3e185</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://staging-ocp-lms.mmsgroup.co.id/perizinan/permohonan/perpanjang</value>
      <webElementGuid>5d7f0bbd-22d8-4048-8707-150a4dc9a8c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-item</value>
      <webElementGuid>8db3c7ea-9ebd-4efc-9b8c-740c8a56caca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>key</name>
      <type>Main</type>
      <value>t-69</value>
      <webElementGuid>aae29b3c-024e-4060-8ae9-476ea44f1b54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                                                        Perpanjangan
                                                                    </value>
      <webElementGuid>c9870a81-49d4-4cdf-b521-cc4e6ee2942e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;topnav-menu-content&quot;)/ul[@class=&quot;navbar-nav active&quot;]/li[@class=&quot;nav-item dropdown active&quot;]/div[@class=&quot;dropdown-menu active&quot;]/div[@class=&quot;dropdown active&quot;]/div[@class=&quot;dropdown-menu active&quot;]/a[@class=&quot;dropdown-item&quot;]</value>
      <webElementGuid>ceb2cde3-4275-4674-bfa1-67600f1b466d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='topnav-menu-content']/ul/li[2]/div/div/div/a[2]</value>
      <webElementGuid>36467060-db8b-4c89-a070-ee89745f6530</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Perpanjangan')]</value>
      <webElementGuid>76a6a68e-2d0d-4109-aa91-e0439cfc5caf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Baru'])[1]/following::a[1]</value>
      <webElementGuid>67b4b26b-a751-46b9-a019-1d12c0ce0483</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Permohonan'])[1]/following::a[2]</value>
      <webElementGuid>81d906db-c4e6-41c9-8b22-72548cd6ea17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Perubahan'])[1]/preceding::a[1]</value>
      <webElementGuid>fb340387-6677-461e-b4d2-1bcf74fc9d32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Daftar Request Perizinan'])[1]/preceding::a[2]</value>
      <webElementGuid>ac15179d-785a-4c8a-9259-8c3ca5bdfd75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Perpanjangan']/parent::*</value>
      <webElementGuid>0833de7d-5ed4-4110-b9fb-9bf5879f27d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://staging-ocp-lms.mmsgroup.co.id/perizinan/permohonan/perpanjang')]</value>
      <webElementGuid>1807d128-db56-4178-95ff-70e7764b1185</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/div/div/div/a[2]</value>
      <webElementGuid>2c418da6-e72b-429b-89a0-498ca27dbd86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://staging-ocp-lms.mmsgroup.co.id/perizinan/permohonan/perpanjang' and (text() = '
                                                                        Perpanjangan
                                                                    ' or . = '
                                                                        Perpanjangan
                                                                    ')]</value>
      <webElementGuid>a159e218-5c4c-453e-9eb9-8adbc1e5f79e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
