<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Ajukan-Permohonan</name>
   <tag></tag>
   <elementGuidId>c8660727-c37b-407f-b5a6-7524984296bb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.fa.fa-plus</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btnAjukan']/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot; Ajukan Permohonan&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>be92a29c-8609-47e3-bb68-64db21306a61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-plus</value>
      <webElementGuid>99167b2f-976b-4e72-a70a-bd2ef03e1386</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnAjukan&quot;)/i[@class=&quot;fa fa-plus&quot;]</value>
      <webElementGuid>4acc2ddb-d288-4204-9af7-35b4f244644f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='btnAjukan']/i</value>
      <webElementGuid>803b995e-8d2d-49da-a104-63fce4e02b97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[2]/div/button/i</value>
      <webElementGuid>70784991-ea99-46cd-bda4-84f043e5d4d4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
