<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_File_tambah-progress-perizinan</name>
   <tag></tag>
   <elementGuidId>4c039995-f208-4f6b-a2ab-fbcb35b6f1b1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#subpermittrackingfilepath</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='subpermittrackingfilepath']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#subpermittrackingfilepath</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>376ba8fd-a888-4003-b974-61f86b025768</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>file</value>
      <webElementGuid>0a0dff70-12df-4c2d-9aa4-4c2176ee1537</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>e8f85234-bf7e-48f6-a70f-f26d6830a67b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>subpermittrackingfilepath</value>
      <webElementGuid>02b5efc7-2f63-46a4-b19a-ce731046018c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>subpermittrackingfilepath</value>
      <webElementGuid>5a1c8ccb-f132-4295-9c46-2de4680885c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>accept</name>
      <type>Main</type>
      <value>.pdf,.png,.jpg,.jpeg,.docx</value>
      <webElementGuid>2baa0fc8-9f39-48d8-93ce-af135b0b3805</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;subpermittrackingfilepath&quot;)</value>
      <webElementGuid>1000da57-b834-4167-80bb-8c27e34a4406</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='subpermittrackingfilepath']</value>
      <webElementGuid>a3dc7ed1-3d93-4b0c-81a9-5b40e94d58fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formData']/div[5]/div[2]/input</value>
      <webElementGuid>97333567-57f0-4d59-b027-32c669b7aaef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[2]/input</value>
      <webElementGuid>0c38f75b-18af-4ace-b61f-30cba4501901</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'file' and @name = 'subpermittrackingfilepath' and @id = 'subpermittrackingfilepath']</value>
      <webElementGuid>7154f4da-8b8b-4158-abf9-baf980e9390c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
