<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Tanggal</name>
   <tag></tag>
   <elementGuidId>6f9a83a7-3b4d-4759-8b7e-2fee5de62167</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#subpermittrackingdate</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='subpermittrackingdate']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#subpermittrackingdate</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>00398433-f2ed-4b98-879d-0c05988a4e59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>date</value>
      <webElementGuid>5ec43811-7f53-4cd9-8554-234d121609ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>8c9323de-d169-474a-b201-958a15c77f68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>subpermittrackingdate</value>
      <webElementGuid>464c93ae-131c-48ca-9543-d57a8cd07f3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>subpermittrackingdate</value>
      <webElementGuid>f96b5701-d771-4674-8ae7-bf008d6a5a9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;subpermittrackingdate&quot;)</value>
      <webElementGuid>9574bfdf-df22-49a2-8ad6-1240aba26423</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='subpermittrackingdate']</value>
      <webElementGuid>53cfbc80-5f7e-497c-b801-bdf3df800b2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='form-status-common']/div/div[2]/input</value>
      <webElementGuid>7364b059-ee35-4ed4-a255-002830c73747</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>81649513-f348-4887-94d3-6e11cfe2c72f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'date' and @name = 'subpermittrackingdate' and @id = 'subpermittrackingdate']</value>
      <webElementGuid>857590c0-766c-4b49-92c7-f4584221ad1c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
