<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Status_tambah-progress-perizinan</name>
   <tag></tag>
   <elementGuidId>6fa54510-0178-4daa-9fce-dabc896a76ae</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#subpermittrackingstatus</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='subpermittrackingstatus']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#subpermittrackingstatus</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>706b764e-98b4-49f8-a81e-2ea7e0b9a6d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-select</value>
      <webElementGuid>38d1a4bd-7f8a-4eed-99f0-4a788601a6ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>subpermittrackingstatus</value>
      <webElementGuid>e70897ce-4de3-40b4-959c-86dc70bfcdd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>subpermittrackingstatus</value>
      <webElementGuid>b06b2025-b843-4f2c-a0b4-2f6add6927e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
									Registrasi permohonan
									Evaluasi
									Perbaikan
									Disetujui
									Ditolak
								</value>
      <webElementGuid>491589bc-198a-493a-bd67-c2687242bbc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;subpermittrackingstatus&quot;)</value>
      <webElementGuid>b5430b86-439b-4c00-9b6f-330a4a816977</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='subpermittrackingstatus']</value>
      <webElementGuid>bf40d46d-4c87-437e-8c88-b4abcf8c2c44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formData']/div/div[2]/select</value>
      <webElementGuid>0d85f125-f769-487f-b6ed-9b8e591af98d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Status'])[3]/following::select[1]</value>
      <webElementGuid>8e03e9cd-7231-450a-bc37-0ccd07f93121</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Perhatian!!!'])[1]/following::select[1]</value>
      <webElementGuid>2d866fdb-c3b7-4034-8f0b-62d7b6425b7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Keterangan'])[3]/preceding::select[1]</value>
      <webElementGuid>3d5d2d29-97ca-4075-a123-01731bf35c0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tanggal'])[1]/preceding::select[1]</value>
      <webElementGuid>a5155936-aa78-4b7e-a6e4-8e9302403014</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/select</value>
      <webElementGuid>5d535396-52a6-4357-b4d9-39d1abf57ddb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'subpermittrackingstatus' and @id = 'subpermittrackingstatus' and (text() = '
									Registrasi permohonan
									Evaluasi
									Perbaikan
									Disetujui
									Ditolak
								' or . = '
									Registrasi permohonan
									Evaluasi
									Perbaikan
									Disetujui
									Ditolak
								')]</value>
      <webElementGuid>8ef5ce58-e452-41fd-b72e-cfd7ebb33b4d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
