<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Detail</name>
   <tag></tag>
   <elementGuidId>ac2be6a5-d99e-416d-bb83-d725893adcae</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.btn.btn-info.btn-sm.m-1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='DataTables_Table_0']/tbody/tr/td[5]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot; Detail&quot;i] >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>a6f4f22f-952b-4871-bc82-10be331b46cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://ocp-mmsgi.alfahuma.biz.id/master/kbli/eyJpdiI6IlRHUDYxK1h1T25Wb2c3U3NmazdtU2c9PSIsInZhbHVlIjoiemZIWjA1UnZOcTRFLzF3TUVxb1lDT3YrWmhsUjR3QlFrUFA3d1JOd2ZnMk5oSHprVVhEeHowc3JidGNlU3pEeCIsIm1hYyI6Ijk0ZThhY2ZjMDg1ZTViOGI3ZDdlN2ZiOTY5ZWQzYmYyNmNiZjAyZTZiZGM0YzBiZGE4MWNmNmNjNjhhZmRjNTIiLCJ0YWciOiIifQ==</value>
      <webElementGuid>f2b7da65-2d40-4852-a3a1-22bc4fcae382</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-info btn-sm m-1</value>
      <webElementGuid>5b7d7c2b-5943-418b-af0d-9d7287629bdd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                         Detail
                    </value>
      <webElementGuid>70da7b56-b6c4-4749-b4d5-89ac0b0ec165</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DataTables_Table_0&quot;)/tbody[1]/tr[@class=&quot;odd&quot;]/td[@class=&quot;text-center&quot;]/a[@class=&quot;btn btn-info btn-sm m-1&quot;]</value>
      <webElementGuid>425c4997-741d-4272-9b55-5252d5ff07ae</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='DataTables_Table_0']/tbody/tr/td[5]/a</value>
      <webElementGuid>bfcdb416-bb5c-493f-a00f-f307e7ab1e71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ENABLE'])[2]/following::a[1]</value>
      <webElementGuid>d238919a-3466-4513-94de-49fe469480bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Real Estat yang Dimiliki Sendiri atau Disewa'])[1]/following::a[1]</value>
      <webElementGuid>7f8d0ad1-2d24-4a93-848c-1fa758b573fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Detail']/parent::*</value>
      <webElementGuid>e364647d-760d-4941-b5ae-38be911c29f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://ocp-mmsgi.alfahuma.biz.id/master/kbli/eyJpdiI6IlRHUDYxK1h1T25Wb2c3U3NmazdtU2c9PSIsInZhbHVlIjoiemZIWjA1UnZOcTRFLzF3TUVxb1lDT3YrWmhsUjR3QlFrUFA3d1JOd2ZnMk5oSHprVVhEeHowc3JidGNlU3pEeCIsIm1hYyI6Ijk0ZThhY2ZjMDg1ZTViOGI3ZDdlN2ZiOTY5ZWQzYmYyNmNiZjAyZTZiZGM0YzBiZGE4MWNmNmNjNjhhZmRjNTIiLCJ0YWciOiIifQ==')]</value>
      <webElementGuid>7bf4525f-5840-4eb0-9229-e886dd5d520d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[5]/a</value>
      <webElementGuid>2d4de1f9-711f-4d5e-b0da-df0201c182c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://ocp-mmsgi.alfahuma.biz.id/master/kbli/eyJpdiI6IlRHUDYxK1h1T25Wb2c3U3NmazdtU2c9PSIsInZhbHVlIjoiemZIWjA1UnZOcTRFLzF3TUVxb1lDT3YrWmhsUjR3QlFrUFA3d1JOd2ZnMk5oSHprVVhEeHowc3JidGNlU3pEeCIsIm1hYyI6Ijk0ZThhY2ZjMDg1ZTViOGI3ZDdlN2ZiOTY5ZWQzYmYyNmNiZjAyZTZiZGM0YzBiZGE4MWNmNmNjNjhhZmRjNTIiLCJ0YWciOiIifQ==' and (text() = '
                         Detail
                    ' or . = '
                         Detail
                    ')]</value>
      <webElementGuid>4b9a33ff-4084-4467-a1db-bee8a5a9956d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
