<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Edit</name>
   <tag></tag>
   <elementGuidId>26a0a6c1-0d44-4a4f-a950-1e63b226daf9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.btn.btn-primary.btn-sm.m-1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='DataTables_Table_0']/tbody/tr/td[5]/a[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot; Edit&quot;i] >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>793cd404-500d-4959-a99f-8981a8104b66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://ocp-mmsgi.alfahuma.biz.id/master/kbli/eyJpdiI6IlRHUDYxK1h1T25Wb2c3U3NmazdtU2c9PSIsInZhbHVlIjoiemZIWjA1UnZOcTRFLzF3TUVxb1lDT3YrWmhsUjR3QlFrUFA3d1JOd2ZnMk5oSHprVVhEeHowc3JidGNlU3pEeCIsIm1hYyI6Ijk0ZThhY2ZjMDg1ZTViOGI3ZDdlN2ZiOTY5ZWQzYmYyNmNiZjAyZTZiZGM0YzBiZGE4MWNmNmNjNjhhZmRjNTIiLCJ0YWciOiIifQ==/edit</value>
      <webElementGuid>f6cecad7-b66d-41b7-b6e1-b9cc1ec9074e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary btn-sm m-1</value>
      <webElementGuid>01a39dfc-6591-4a54-b50f-efaad48595b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                             Edit
                        </value>
      <webElementGuid>f61ae094-ab08-416c-a54f-87cb7fc39fe0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DataTables_Table_0&quot;)/tbody[1]/tr[@class=&quot;odd&quot;]/td[@class=&quot;text-center&quot;]/a[@class=&quot;btn btn-primary btn-sm m-1&quot;]</value>
      <webElementGuid>7e75af50-2e5a-4927-b59e-8cf6b016f9a7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='DataTables_Table_0']/tbody/tr/td[5]/a[2]</value>
      <webElementGuid>52b7398e-25c8-4573-8a84-3506669075ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ENABLE'])[2]/following::a[2]</value>
      <webElementGuid>09363665-e1c1-4b04-9fe1-e18c58bfee1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Penyiapan Lahan'])[1]/preceding::a[1]</value>
      <webElementGuid>61988793-86c8-4ef0-8ec8-04ca1aac4ca4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Edit']/parent::*</value>
      <webElementGuid>dcd07940-04e7-4fab-bc52-66c5691a0506</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://ocp-mmsgi.alfahuma.biz.id/master/kbli/eyJpdiI6IlRHUDYxK1h1T25Wb2c3U3NmazdtU2c9PSIsInZhbHVlIjoiemZIWjA1UnZOcTRFLzF3TUVxb1lDT3YrWmhsUjR3QlFrUFA3d1JOd2ZnMk5oSHprVVhEeHowc3JidGNlU3pEeCIsIm1hYyI6Ijk0ZThhY2ZjMDg1ZTViOGI3ZDdlN2ZiOTY5ZWQzYmYyNmNiZjAyZTZiZGM0YzBiZGE4MWNmNmNjNjhhZmRjNTIiLCJ0YWciOiIifQ==/edit')]</value>
      <webElementGuid>f0e594c1-5f4c-4ee2-bdf4-b28c59308eac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[5]/a[2]</value>
      <webElementGuid>5acef0da-29df-4d27-a1f2-da7d2f425bd0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://ocp-mmsgi.alfahuma.biz.id/master/kbli/eyJpdiI6IlRHUDYxK1h1T25Wb2c3U3NmazdtU2c9PSIsInZhbHVlIjoiemZIWjA1UnZOcTRFLzF3TUVxb1lDT3YrWmhsUjR3QlFrUFA3d1JOd2ZnMk5oSHprVVhEeHowc3JidGNlU3pEeCIsIm1hYyI6Ijk0ZThhY2ZjMDg1ZTViOGI3ZDdlN2ZiOTY5ZWQzYmYyNmNiZjAyZTZiZGM0YzBiZGE4MWNmNmNjNjhhZmRjNTIiLCJ0YWciOiIifQ==/edit' and (text() = '
                             Edit
                        ' or . = '
                             Edit
                        ')]</value>
      <webElementGuid>ad9e6af0-93be-402d-b273-b2c8f2355774</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
