<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_KBLI</name>
   <tag></tag>
   <elementGuidId>f4f38974-289a-4a5b-9a0d-efd876ce4a87</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='topnav-menu-content']/ul/li[4]/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;KBLI&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>ed62b806-f4b6-41f3-b088-cc6fbd91f857</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://ocp-mmsgi.alfahuma.biz.id/master/kbli</value>
      <webElementGuid>2227053d-6ed0-4a86-9c65-16b869954f87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-item</value>
      <webElementGuid>33ca4277-b2a3-495a-b109-485438d3cff3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>key</name>
      <type>Main</type>
      <value>t-60</value>
      <webElementGuid>c0b289d5-37b4-4eb9-ab92-90219f5a04f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                                        KBLI
                                                    </value>
      <webElementGuid>23d7b920-8403-46ff-9680-59793c2ba532</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;topnav-menu-content&quot;)/ul[@class=&quot;navbar-nav active&quot;]/li[@class=&quot;nav-item dropdown&quot;]/div[@class=&quot;dropdown-menu&quot;]/a[@class=&quot;dropdown-item&quot;]</value>
      <webElementGuid>bf940c34-8f7e-4324-9497-4ad3162349d9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='topnav-menu-content']/ul/li[4]/div/a</value>
      <webElementGuid>d330d0ba-8fa2-4b8e-9ba9-bb56e974d1a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'KBLI')]</value>
      <webElementGuid>63c79819-9989-4677-ab6d-f04818ca1edc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Master Data'])[1]/following::a[1]</value>
      <webElementGuid>7f93e972-e0d0-45df-8b67-a98bfdf96721</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Permintaan Dana'])[1]/following::a[2]</value>
      <webElementGuid>5c01c152-c2b7-460e-8f91-b660773559ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Category Permit'])[1]/preceding::a[1]</value>
      <webElementGuid>67f9f388-d686-45b5-8737-453a7edeb8ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Type Permit'])[1]/preceding::a[2]</value>
      <webElementGuid>966263d0-57cd-4b8f-aafb-d284c7767adb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='KBLI']/parent::*</value>
      <webElementGuid>40b8777f-a8c8-4266-8355-c903e0f9bfad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://ocp-mmsgi.alfahuma.biz.id/master/kbli')]</value>
      <webElementGuid>c47c777b-0e00-4e51-b41b-7f42d7983769</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/div/a</value>
      <webElementGuid>9fab84dc-e003-4ff1-9a76-f8324f948a98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://ocp-mmsgi.alfahuma.biz.id/master/kbli' and (text() = '
                                                        KBLI
                                                    ' or . = '
                                                        KBLI
                                                    ')]</value>
      <webElementGuid>0ef6b4ec-33c7-4bab-80a4-9d2bc8349a75</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
