<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Detail-perizinan-Utama</name>
   <tag></tag>
   <elementGuidId>16ee7859-94c9-41ef-8382-05516b801d36</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@onclick=&quot;redirectDetail('0199c0e5-c2e6-71e6-adec-8d32e35c5478')&quot;]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.btn.btn-info.btn-sm</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=row[name=&quot;MHU Coal Perizinan Lingkungan - Pengelolaan Limbah 23456 2025-10-30 2025-10-10 Menteri Energi dan Sumber Daya Mineral 3 󰈈 Detail&quot;i] >> div</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>59434548-d260-40ba-99a4-861297241bcf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>redirectDetail('0199c0e5-c2e6-71e6-adec-8d32e35c5478')</value>
      <webElementGuid>2b989395-2baf-4b5d-8baa-649c2c87a73a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-info btn-sm</value>
      <webElementGuid>fd436f28-6f67-401c-a44a-bd780aab64d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>  Detail </value>
      <webElementGuid>ed29d8ab-cd85-41c5-9e01-ffcdb3197ef5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DataTables_Table_0&quot;)/tbody[1]/tr[@class=&quot;odd&quot;]/td[@class=&quot;text-center&quot;]/div[@class=&quot;btn btn-info btn-sm&quot;]</value>
      <webElementGuid>9bf73f91-19b6-4418-8f7f-a7a621ce2edb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@onclick=&quot;redirectDetail('0199c0e5-c2e6-71e6-adec-8d32e35c5478')&quot;]</value>
      <webElementGuid>727faa5c-d5e9-411e-b730-ed08f6ee2bc9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='DataTables_Table_0']/tbody/tr/td[8]/div</value>
      <webElementGuid>7c4b68bd-9595-42b6-83e3-7c40b5722120</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Menteri Energi dan Sumber Daya Mineral'])[1]/following::div[1]</value>
      <webElementGuid>0bdbc356-3146-4b85-b1c1-4daa23d1ce2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Perizinan Lingkungan - Pengelolaan Limbah'])[1]/following::div[1]</value>
      <webElementGuid>aa1eb5ce-096e-458d-8362-6cf7d7d9595f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mitra Nikel Utama'])[2]/preceding::div[1]</value>
      <webElementGuid>28b3fa9d-92f0-427c-b379-dc2f20e1342c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Perizinan Lingkungan - Bongkar Batu'])[1]/preceding::div[1]</value>
      <webElementGuid>57f21c0a-aef4-41d3-9e6f-efb2bd9d21dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Detail']/parent::*</value>
      <webElementGuid>1ebccba6-ac9d-43eb-94bc-ee95f2d57bea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[8]/div</value>
      <webElementGuid>fb9f7f33-8707-448f-8265-02f866645941</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '  Detail ' or . = '  Detail ')]</value>
      <webElementGuid>b22f4d0f-9853-4bb4-a674-39a16b06089b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
