<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>th_sorting_tanggal-penerbit</name>
   <tag></tag>
   <elementGuidId>e3340832-9442-4020-9757-5b8f2908f1b0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='DataTables_Table_0_wrapper']/div[2]/div/div/div/div/table/thead/tr/th[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Tanggal Penerbit: activate to sort column ascending&quot;i >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>th</value>
      <webElementGuid>8a1ece62-12f9-40de-90b1-3cf51b7f00de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sorting</value>
      <webElementGuid>3d34143b-aaa2-4d76-a1f4-bb32dbb5e302</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>2f208098-aeea-48ce-aeea-c029b412d93f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>DataTables_Table_0</value>
      <webElementGuid>ef0dc4f4-1dd5-474c-8232-fc7525f3cb46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rowspan</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>2d54c9d9-a039-428c-ae03-efbc8f0279d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>colspan</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>3204c9d1-ae99-45a0-9606-453738da501d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Tanggal Penerbit: activate to sort column ascending</value>
      <webElementGuid>b4c84233-c38a-46b5-99d0-50b82296ad17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Tanggal Penerbit</value>
      <webElementGuid>b12a1b9c-ab9a-4b8a-a7e9-3050eca44180</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DataTables_Table_0_wrapper&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-12&quot;]/div[@class=&quot;dataTables_scroll&quot;]/div[@class=&quot;dataTables_scrollHead&quot;]/div[@class=&quot;dataTables_scrollHeadInner&quot;]/table[@class=&quot;table table-bordered table-sm table-striped dt-responsive nowrap w-100 yajra-datatable-utama mb-4 dataTable no-footer&quot;]/thead[@class=&quot;table-dark&quot;]/tr[1]/th[@class=&quot;sorting&quot;]</value>
      <webElementGuid>57144e54-d517-49b0-8b01-217ba98cac02</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='DataTables_Table_0_wrapper']/div[2]/div/div/div/div/table/thead/tr/th[4]</value>
      <webElementGuid>ca865500-6c59-4fcc-abc0-66bd84ac61a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nomor Perizinan'])[1]/following::th[1]</value>
      <webElementGuid>f72a3d77-7422-4fc0-83a3-e1abac85c15a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nama Perizinan'])[1]/following::th[2]</value>
      <webElementGuid>ba97fab6-832f-46c3-bb4e-a430954b9890</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Masa Berlaku'])[1]/preceding::th[1]</value>
      <webElementGuid>f8ed9795-e8ce-4441-a09d-81077e945801</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Instansi Penerbit'])[1]/preceding::th[2]</value>
      <webElementGuid>3d3f30c5-d281-4e6f-b687-cfb4d9a6451a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Tanggal Penerbit']/parent::*</value>
      <webElementGuid>fd8c3fc6-103d-4f2d-8278-a539685183a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th[4]</value>
      <webElementGuid>b1416b42-9ee1-4bc9-827b-7cb85ade62fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//th[(text() = 'Tanggal Penerbit' or . = 'Tanggal Penerbit')]</value>
      <webElementGuid>fbbb912e-14f7-401d-b2a0-1451f1d72757</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
