<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Upload-Dok-pendukung</name>
   <tag></tag>
   <elementGuidId>996c93e3-1aed-465e-b02b-0706592e62a7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='file_dokumen[]']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;file_dokumen[]&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>input[name=&quot;file_dokumen\[\]&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f992e8a2-e469-4f4e-80a4-de5b096b02ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>file</value>
      <webElementGuid>29b34e2d-ca14-4060-ac64-f5898c637267</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>file_dokumen[]</value>
      <webElementGuid>f2f6bdb6-10e3-439b-9994-a5d85501292f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>5a5adcbd-5a49-4785-89de-255bdb40c115</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>accept</name>
      <type>Main</type>
      <value>.pdf,.png,.jpg,.jpeg,.docx</value>
      <webElementGuid>43062bfc-f2a8-4fe1-af2c-2f7ae2ea621d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dokumen-container&quot;)/div[@class=&quot;dokumen-item d-flex align-items-center mb-2&quot;]/input[@class=&quot;form-control&quot;]</value>
      <webElementGuid>23668679-b6f0-4836-9f67-42f9a1e90646</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='file_dokumen[]']</value>
      <webElementGuid>cf312b93-2971-4e33-aae5-a9802e8fff3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dokumen-container']/div/input[2]</value>
      <webElementGuid>f5e4be64-8589-40e9-901c-a7e550447c46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[2]</value>
      <webElementGuid>f8e66a03-5cbe-41fa-b66c-4ec7d302fd2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'file' and @name = 'file_dokumen[]']</value>
      <webElementGuid>464b1a9d-4923-49b9-8bdf-2ea76b583151</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
