<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_targetWaktu</name>
   <tag></tag>
   <elementGuidId>cfa4b829-c4e3-4127-b23d-c52ba15adbb0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#targetWaktu</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='targetWaktu']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#targetWaktu</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9eb275a6-ef71-4c99-b447-66363895a93a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>date</value>
      <webElementGuid>ba40892f-71c1-46ac-baee-eedd23fae8c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>d4acdf91-8b46-4023-a4ba-e1952d60786f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>permittargettime</value>
      <webElementGuid>87597beb-cef8-4e02-8ac6-f790343bd731</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>targetWaktu</value>
      <webElementGuid>8bc8dd00-8eff-4c3c-b86b-91c16963ebbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;targetWaktu&quot;)</value>
      <webElementGuid>4ede873a-e31e-4de9-ae1e-db3e776b5cf3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='targetWaktu']</value>
      <webElementGuid>d85a4be1-8aef-40f5-80d9-60b8ff9c8147</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form-permohonan-perpanjangan']/div/div[3]/input</value>
      <webElementGuid>29030073-a353-4175-a7c0-9499b47f6e07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>a1bca4e6-f550-413f-9ead-10dd36fff712</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'date' and @name = 'permittargettime' and @id = 'targetWaktu']</value>
      <webElementGuid>ab44b9f8-998c-442d-bc8c-9c9bd09dd766</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
