<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_jenis-perizinan-yg-diajukan</name>
   <tag></tag>
   <elementGuidId>c62dcf43-526d-48bd-a5d4-0d9022fe5c30</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='formCard']/div[2]/select</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#formCard div >> internal:has-text=&quot;Jenis Perizinan yang Diajukan * Izin Usaha Jasa Pertambangan Lainnya&quot;i >> internal:role=combobox</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>5f4b8480-441e-447a-a66d-41d6a749674d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-select</value>
      <webElementGuid>cba66b07-c4f7-457f-8c69-eb9e2a84986b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
          Izin Usaha Jasa Pertambangan
          Lainnya
        </value>
      <webElementGuid>78c7876d-88f7-4c90-84dd-6500d222783f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;formCard&quot;)/div[@class=&quot;mb-3&quot;]/select[@class=&quot;form-select&quot;]</value>
      <webElementGuid>fa8e337e-7364-42ea-90ae-39b33385980a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='formCard']/div[2]/select</value>
      <webElementGuid>36958fb3-5194-4f59-8cb3-09aefb544a26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[1]/following::select[1]</value>
      <webElementGuid>aff54fbc-5793-45f3-b678-7bd6dddc3389</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[2]/preceding::select[1]</value>
      <webElementGuid>4817eea0-0dca-458f-a052-4a13898e65d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/select</value>
      <webElementGuid>4ad9d97d-d515-445c-ab4f-a529a0af43d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[(text() = '
          Izin Usaha Jasa Pertambangan
          Lainnya
        ' or . = '
          Izin Usaha Jasa Pertambangan
          Lainnya
        ')]</value>
      <webElementGuid>b4b18fc3-66aa-42d6-8f80-ebc3cb611fb0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
