<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Pilih-Company</name>
   <tag></tag>
   <elementGuidId>972c8340-f9e1-463b-a64d-bf36e0f5e629</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#select2-companyid-y6-container</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-companyid-y6-container']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#select2-companyid-y6-container</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>89e610a0-6fa6-4f80-a9cd-3adc4b297f66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>9ceef1d2-a034-4eb5-8b09-1cb28e52104d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-companyid-y6-container</value>
      <webElementGuid>bb3cfd31-677d-4020-838c-1b1d89723fd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>fb0119e2-38ee-4071-9806-0f3da40b2b6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>8dad5033-943f-412e-b8b7-aa853fd468ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>-- Pilih --</value>
      <webElementGuid>3ecb7d42-799d-499a-bc33-3946f9d24653</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>-- Pilih --</value>
      <webElementGuid>3144e2af-d9cb-4dc8-a25c-d72da2d6f467</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-companyid-y6-container&quot;)</value>
      <webElementGuid>5f44e697-5e42-4584-9db6-5b10c7ae6095</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-companyid-y6-container']</value>
      <webElementGuid>9933ad36-c427-4b80-b73a-143f2a408e30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form-permohonan-perpanjangan']/div/div/span/span/span/span</value>
      <webElementGuid>cb17d3c2-28fb-4adf-b2c9-7a95ca8a9e1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pilih Company'])[1]/following::span[4]</value>
      <webElementGuid>d315288b-0c1b-4baa-a7b5-bb90ea73b451</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Permohonan Perpanjangan'])[1]/following::span[4]</value>
      <webElementGuid>a5556404-ce6e-4d7b-880c-2215e184bd17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[1]/preceding::span[3]</value>
      <webElementGuid>dcb1d5c9-20ee-405e-9814-e628663873ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span/span/span</value>
      <webElementGuid>43c04a2a-e6e4-4551-84b5-3145645f0a34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-companyid-y6-container' and @title = '-- Pilih --' and (text() = '-- Pilih --' or . = '-- Pilih --')]</value>
      <webElementGuid>1f211f33-db3c-4659-a82d-3044a7af9a61</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
