<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Detail-type-permit</name>
   <tag></tag>
   <elementGuidId>ca505a85-4d63-4e09-bc94-ce622d961f54</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='DataTables_Table_0']/tbody/tr/td[7]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.btn.btn-info.btn-sm.m-1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot; Detail&quot;i] >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>0f1e2a0e-e0a4-4914-8bdb-255ad70d6358</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://ocp-mmsgi.alfahuma.biz.id/master/type_permit/eyJpdiI6ImprVEYxZHdrSTNCQlIxMVVuWUlnQmc9PSIsInZhbHVlIjoiOWVzcE5wSVYyZDFzUVpnbExhVlNqOGNjbFgvY29vVWJwUi9XY3o1d2JTR3Qyd3pHQTZmTFN6V2xJNEZmRUZpQyIsIm1hYyI6ImYyYTAzNGJjNzBjMWI0YjY5YTkzMWExMTQ3Yzg2MzJiMWUxZmE0NWZmM2FiYzdiZDFjNmRkYWNkY2E0MDU4NjEiLCJ0YWciOiIifQ==</value>
      <webElementGuid>bc932400-59a7-4c8b-88c4-be99a2855fba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-info btn-sm m-1</value>
      <webElementGuid>270394a7-0400-43ed-8d33-d16737d07360</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                         Detail
                    </value>
      <webElementGuid>c9cc8a56-cb63-49ad-8338-c46279d7e291</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DataTables_Table_0&quot;)/tbody[1]/tr[@class=&quot;odd&quot;]/td[@class=&quot;text-center&quot;]/a[@class=&quot;btn btn-info btn-sm m-1&quot;]</value>
      <webElementGuid>f264f322-8a59-4fd0-a1b2-7d31bead5369</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='DataTables_Table_0']/tbody/tr/td[7]/a</value>
      <webElementGuid>7b83c18a-640f-4fdd-8c52-e9d1ad03f491</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ENABLE'])[2]/following::a[1]</value>
      <webElementGuid>82e10d1d-5fc0-41f6-ba51-8353d703dc91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Real Estat yang Dimiliki Sendiri atau Disewa'])[2]/following::a[1]</value>
      <webElementGuid>92ae449a-ce90-4445-ade6-c817ad880d7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Detail']/parent::*</value>
      <webElementGuid>eba13b19-a7c3-4db5-b538-db2e63bc08ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://ocp-mmsgi.alfahuma.biz.id/master/type_permit/eyJpdiI6ImprVEYxZHdrSTNCQlIxMVVuWUlnQmc9PSIsInZhbHVlIjoiOWVzcE5wSVYyZDFzUVpnbExhVlNqOGNjbFgvY29vVWJwUi9XY3o1d2JTR3Qyd3pHQTZmTFN6V2xJNEZmRUZpQyIsIm1hYyI6ImYyYTAzNGJjNzBjMWI0YjY5YTkzMWExMTQ3Yzg2MzJiMWUxZmE0NWZmM2FiYzdiZDFjNmRkYWNkY2E0MDU4NjEiLCJ0YWciOiIifQ==')]</value>
      <webElementGuid>880164a8-af3c-4f02-a4c4-092535527a78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[7]/a</value>
      <webElementGuid>886038a8-6de3-47ba-8c8b-16d0cb3501ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://ocp-mmsgi.alfahuma.biz.id/master/type_permit/eyJpdiI6ImprVEYxZHdrSTNCQlIxMVVuWUlnQmc9PSIsInZhbHVlIjoiOWVzcE5wSVYyZDFzUVpnbExhVlNqOGNjbFgvY29vVWJwUi9XY3o1d2JTR3Qyd3pHQTZmTFN6V2xJNEZmRUZpQyIsIm1hYyI6ImYyYTAzNGJjNzBjMWI0YjY5YTkzMWExMTQ3Yzg2MzJiMWUxZmE0NWZmM2FiYzdiZDFjNmRkYWNkY2E0MDU4NjEiLCJ0YWciOiIifQ==' and (text() = '
                         Detail
                    ' or . = '
                         Detail
                    ')]</value>
      <webElementGuid>cbfd5bc8-a300-4c9c-88ab-f48eb6937627</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
