<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Upload-BuktiKodeBilling</name>
   <tag></tag>
   <elementGuidId>6c47fca6-4085-48e4-80b4-aa8332a7676d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='permitfundsbillingfilepath']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#permitfundsbillingfilepath</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#permitfundsbillingfilepath</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>83b036ab-afcd-4f64-a0ca-201866aeaf29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>file</value>
      <webElementGuid>fc43ccf3-ab1f-464e-92d6-3e152cf0e1de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>1cb42ce3-c3fc-4f6d-951b-1da7e8bfb9b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>permitfundsbillingfilepath</value>
      <webElementGuid>e8b9a01c-f5a4-4ca7-a202-4977e9f66487</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>permitfundsbillingfilepath</value>
      <webElementGuid>dddf3ad2-23f9-44c9-8c3f-8d0438d62b8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>accept</name>
      <type>Main</type>
      <value>.pdf,.png,.jpg,.jpeg,.docx</value>
      <webElementGuid>cf8ec33f-fbae-4d41-a06a-1871c6336381</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;permitfundsbillingfilepath&quot;)</value>
      <webElementGuid>ccfc8032-7038-4409-b976-1972be5af8b8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='permitfundsbillingfilepath']</value>
      <webElementGuid>3086354c-cddb-404f-b11d-7281882c3b0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modalContentPermintaanDana']/div[9]/div[2]/input</value>
      <webElementGuid>54efbaa2-be2d-4441-b322-e317b0321eb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div[2]/input</value>
      <webElementGuid>598d1230-89d2-494d-844d-e3ef2a298dbf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'file' and @name = 'permitfundsbillingfilepath' and @id = 'permitfundsbillingfilepath']</value>
      <webElementGuid>00d8caf5-b094-4362-b638-fd7672e7df7a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
