<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nama-Billing</name>
   <tag></tag>
   <elementGuidId>17a9666c-2051-428a-be97-37880334f770</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='permitfundsnamebilling']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#permitfundsnamebilling</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#permitfundsnamebilling</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d613f49b-faf2-452d-bfdb-c13e0f55126e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2660959b-20e3-4183-9b5c-99c352ea5bdc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>c8ac998e-b3a2-4e55-9094-cc2123dc52cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>permitfundsnamebilling</value>
      <webElementGuid>47476250-c6ec-4452-b070-dbb72e7539fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>permitfundsnamebilling</value>
      <webElementGuid>f1acd8e4-a774-4326-9bf4-0d697f4e38b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;permitfundsnamebilling&quot;)</value>
      <webElementGuid>2691d0a6-ea96-4887-b7cb-a49d48fc26be</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='permitfundsnamebilling']</value>
      <webElementGuid>f4b2afc0-4dd0-432f-9780-ded360a4b8b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modalContentPermintaanDana']/div[5]/div[2]/input</value>
      <webElementGuid>30eb6ed5-72f4-4014-9144-ff825806dd47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[2]/input</value>
      <webElementGuid>01194a7a-2e07-4efb-b9f8-6a7d1ef2ec09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'permitfundsnamebilling' and @id = 'permitfundsnamebilling']</value>
      <webElementGuid>aaed014c-a876-40bd-8207-b94964833888</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
