<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_EDIT</name>
   <tag></tag>
   <elementGuidId>0a6592ab-20d1-4c1a-ae60-5e564473c4f0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='DataTables_Table_0']/tbody/tr/td[5]/a[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.btn.btn-primary.btn-sm.m-1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot; Edit&quot;i] >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>8677d717-f90c-443e-bf7b-172e12c7bbe5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://ocp-mmsgi.alfahuma.biz.id/master/authority/eyJpdiI6ImtydDhCZGp2RjhQSUZ3bVdTSGFtUWc9PSIsInZhbHVlIjoiUms0YnNSbzlsNzNFY08vT3BXSklhcnhBZ1IxbmNCajJJaDVjL0U3ZS9CWU4rYlVmYjRRaENLa0c5MHhqRjFSNiIsIm1hYyI6IjdiOGVmOWI1Y2VhZDdkZjllMmY3MGQ2N2FhNzA3NGFjOWNjYmEwODhlOWY2ZThmMDIxOGMxNGRiNmU3Yzg0NjUiLCJ0YWciOiIifQ==/edit</value>
      <webElementGuid>89923e23-6e56-4e06-944e-25fae4477048</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary btn-sm m-1</value>
      <webElementGuid>99ab53e3-b5e0-473a-8282-e4460ac64dd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                             Edit
                        </value>
      <webElementGuid>aa1f4bac-a543-410e-92fb-2e248669809e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DataTables_Table_0&quot;)/tbody[1]/tr[@class=&quot;odd&quot;]/td[@class=&quot;text-center&quot;]/a[@class=&quot;btn btn-primary btn-sm m-1&quot;]</value>
      <webElementGuid>f2e95bd2-e0f6-411a-85c0-643177a2348a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='DataTables_Table_0']/tbody/tr/td[5]/a[2]</value>
      <webElementGuid>981c083e-149d-4ab1-bd20-c8e69cd79e7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ENABLE'])[2]/following::a[2]</value>
      <webElementGuid>d3bfff96-5f95-4b92-bc01-a7498835f9e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Menteri Energi dan Sumber Daya Mineral'])[1]/preceding::a[1]</value>
      <webElementGuid>f1263b1b-3263-49ca-85e0-9d8473967e48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Edit']/parent::*</value>
      <webElementGuid>f034c608-2dcb-4f29-b1c8-6723d8ebe4e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://ocp-mmsgi.alfahuma.biz.id/master/authority/eyJpdiI6ImtydDhCZGp2RjhQSUZ3bVdTSGFtUWc9PSIsInZhbHVlIjoiUms0YnNSbzlsNzNFY08vT3BXSklhcnhBZ1IxbmNCajJJaDVjL0U3ZS9CWU4rYlVmYjRRaENLa0c5MHhqRjFSNiIsIm1hYyI6IjdiOGVmOWI1Y2VhZDdkZjllMmY3MGQ2N2FhNzA3NGFjOWNjYmEwODhlOWY2ZThmMDIxOGMxNGRiNmU3Yzg0NjUiLCJ0YWciOiIifQ==/edit')]</value>
      <webElementGuid>e490aaaf-6e98-4672-9e7f-7cb8bb2765af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[5]/a[2]</value>
      <webElementGuid>ff645b5b-c4de-46af-af4a-ab657d48f416</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://ocp-mmsgi.alfahuma.biz.id/master/authority/eyJpdiI6ImtydDhCZGp2RjhQSUZ3bVdTSGFtUWc9PSIsInZhbHVlIjoiUms0YnNSbzlsNzNFY08vT3BXSklhcnhBZ1IxbmNCajJJaDVjL0U3ZS9CWU4rYlVmYjRRaENLa0c5MHhqRjFSNiIsIm1hYyI6IjdiOGVmOWI1Y2VhZDdkZjllMmY3MGQ2N2FhNzA3NGFjOWNjYmEwODhlOWY2ZThmMDIxOGMxNGRiNmU3Yzg0NjUiLCJ0YWciOiIifQ==/edit' and (text() = '
                             Edit
                        ' or . = '
                             Edit
                        ')]</value>
      <webElementGuid>336e4655-07a1-4644-9af8-2f5d51396250</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
