<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Disable</name>
   <tag></tag>
   <elementGuidId>4435359b-384b-403c-a382-e106a30deab5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[6]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.btn.btn-danger.btn-sm</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=row[name=&quot;1 Menteri Pekerjaan Umum dan Perumahan Rakyat Menteri Pekerjaan Umum dan Perumahan Rakyat ENABLE  Detail  Edit  Disable&quot;i] >> internal:role=button</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>56691c75-cfd0-42cb-b1ac-7d36b8475c97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>7334ae4d-9018-4445-aee8-a5d4d93a53c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-danger btn-sm</value>
      <webElementGuid>d6806c50-dd38-4406-805c-7088aa514ec4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>changeStatus('https://ocp-mmsgi.alfahuma.biz.id/master/authority/eyJpdiI6ImtydDhCZGp2RjhQSUZ3bVdTSGFtUWc9PSIsInZhbHVlIjoiUms0YnNSbzlsNzNFY08vT3BXSklhcnhBZ1IxbmNCajJJaDVjL0U3ZS9CWU4rYlVmYjRRaENLa0c5MHhqRjFSNiIsIm1hYyI6IjdiOGVmOWI1Y2VhZDdkZjllMmY3MGQ2N2FhNzA3NGFjOWNjYmEwODhlOWY2ZThmMDIxOGMxNGRiNmU3Yzg0NjUiLCJ0YWciOiIifQ==/DISABLE', $(this))</value>
      <webElementGuid>cd82a62a-7c08-4e39-baf8-70a68899425b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-status</name>
      <type>Main</type>
      <value>ENABLE</value>
      <webElementGuid>4fd26c17-5745-460d-919c-19388cfcd5ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                             Disable
                        </value>
      <webElementGuid>5b9f83c5-7f20-4f23-a3a9-7dbd6c44d290</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DataTables_Table_0&quot;)/tbody[1]/tr[@class=&quot;odd&quot;]/td[@class=&quot;text-center&quot;]/button[@class=&quot;btn btn-danger btn-sm&quot;]</value>
      <webElementGuid>e438fdff-b9c3-4c4a-8685-68e0bbee9033</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[6]</value>
      <webElementGuid>0b3a333f-8a39-4cb7-84b3-a76ee45ff5a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='DataTables_Table_0']/tbody/tr/td[5]/button</value>
      <webElementGuid>8face5fe-264e-4e62-aede-f0155b49271e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Menteri Energi dan Sumber Daya Mineral'])[1]/preceding::button[1]</value>
      <webElementGuid>2c444159-171f-4286-9847-98f0da0bd88b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Menteri Energi dan Sumber Daya Mineral'])[2]/preceding::button[1]</value>
      <webElementGuid>061af751-23dd-4fe4-9f2d-dc7c21671062</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Disable']/parent::*</value>
      <webElementGuid>49322347-bb7e-41e3-9c63-43199579309d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[5]/button</value>
      <webElementGuid>6854bc06-9d59-4cf0-90d1-623466e9634a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = '
                             Disable
                        ' or . = '
                             Disable
                        ')]</value>
      <webElementGuid>84e3982a-98bc-4fee-9db3-5fc3bc1c7d16</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
