<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_LEAD TIMEPENGURUSAN IZIN</name>
   <tag></tag>
   <elementGuidId>f545681e-3999-4fb1-bf79-1c36f37dc923</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='layout-wrapper']/div[2]/div/div/div[2]/div/div[5]/div/div/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.d-flex.align-items-center.mb-2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;12 hari&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>4814c718-877b-4211-b45e-30aebfd092e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>d-flex align-items-center mb-2</value>
      <webElementGuid>28a47d93-aa57-416f-81f9-91a61952a66b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
								12
								hari
							</value>
      <webElementGuid>63706498-4cfe-40e9-ad38-f891708e164b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;layout-wrapper&quot;)/div[@class=&quot;main-content&quot;]/div[@class=&quot;page-content&quot;]/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;card&quot;]/div[@class=&quot;card-body&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-4&quot;]/div[@class=&quot;card card-link&quot;]/div[@class=&quot;card-body bg-izin rounded-3&quot;]/div[@class=&quot;d-flex align-items-center mb-2&quot;]</value>
      <webElementGuid>4f3d21fd-0bd8-4f41-8feb-500e94dfb571</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='layout-wrapper']/div[2]/div/div/div[2]/div/div[5]/div/div/div/div</value>
      <webElementGuid>d339079d-5903-4f45-b568-b24f466fefd7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lead Time'])[1]/following::div[5]</value>
      <webElementGuid>33812f6d-fa93-48b2-bfa7-3b39f85900f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tgl Permintaan'])[1]/preceding::div[1]</value>
      <webElementGuid>c35f0ea1-338d-436d-8b85-660262f4b9c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[5]/div/div/div/div</value>
      <webElementGuid>2afc0fb2-1d53-4796-b436-822a0278519a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '
								12
								hari
							' or . = '
								12
								hari
							')]</value>
      <webElementGuid>358e22b9-6bb6-4d78-9f74-71d190f3613a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
